### ISSUE TITLE
Hide the function definition scratch window on complete

### ISSUE THREAD

**Issue by pag** [ervandew/eclim#121]
Hi,

When I start completing a Java function a scratch window is opened above the current window showing type information and more details. Is there any way to make it close when the completion popup closes? It's annoying because it wastes vertical space showing a function definition that I don't care about after I've finished completion.

Thanks! (And thanks for eclim, it's made my life much better)

**Comment by ranma1988** [comment]
autocmd CompleteDone * pclose

**Comment by puremourning** [comment]
or:

https://github.com/Valloric/YouCompleteMe#the-gycm_autoclose_preview_window_after_completion-option
