### ISSUE TITLE
Installation of eclim fails on MacOS w/ MyEclipse

### ISSUE THREAD

**Issue by blueyed** [ervandew/eclim#146]
I am trying to install eclim on MacOS (Mountain Lion), which fails as follows after selecting the Eclipse path (where I chose /Applications/Genuitec/Common/):

> java.lang.RuntimeException: error:  out: An error has occurred. See the log file
> /Applications/Genuitec/Common/configuration/1345458976070.log.
>   at org.eclim.installer.step.EclipseInfo.installInstallerPlugin(EclipseInfo.java:183)
>   at org.eclim.installer.step.EclipseInfoStep$1.run(EclipseInfoStep.java:67)
>   at foxtrot.AbstractWorkerThread$1.run(AbstractWorkerThread.java:40)
>   at java.security.AccessController.doPrivileged(Native Method)
>   at foxtrot.AbstractWorkerThread.runTask(AbstractWorkerThread.java:36)
>   at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:199)
>   at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:182)
>   at java.lang.Thread.run(Thread.java:722)

The referenced log file looks as follows:

> % cat /Applications/Genuitec/Common/configuration/1345458976070.log                                                                                              MacOS 12.0 (x86_64)
> !SESSION 2012-08-20 12:36:15.730 -----------------------------------------------
> eclipse.buildId=unknown
> java.version=1.6.0_33
> java.vendor=Apple Inc.
> BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
> Framework arguments:  -application org.eclipse.equinox.p2.director -repository file:///var/folders/k9/k7gbksbs2d51dg4npcl_3fkm0000gn/T/formic_795352351/update -installIU org.eclim.installer.feature.group
> Command-line arguments:  -clean -application org.eclipse.equinox.p2.director -repository file:///var/folders/k9/k7gbksbs2d51dg4npcl_3fkm0000gn/T/formic_795352351/update -installIU org.eclim.installer.feature.group
> 
> !ENTRY org.eclipse.osgi 4 0 2012-08-20 12:36:16.495
> !MESSAGE Application error
> !STACK 1
> java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
>   at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:74)
>   at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
>   at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
>   at java.lang.reflect.Method.invoke(Method.java:597)
>   at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
>   at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
>   at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
>   at org.eclipse.equinox.launcher.Main.main(Main.java:1414)

I have installed Java from Apple, which gets triggered after opening "Java Preferences".
I have also tried installing the latest SDK from Oracle (1.7.0_06).

The output on the terminal is:

> % java -jar eclim_2.2.0.jar                                                                                                                                      MacOS 12.0 (x86_64)
> Buildfile: installer.xml
> 2012-08-20 12:52:56,484 INFO  [org.formic.Installer] Running Installer...
> 2012-08-20 12:53:04,840 INFO  [org.formic.util.CommandExecutor] which mvim
> 2012-08-20 12:53:04,883 INFO  [org.eclim.installer.step.VimStep] which mvim: /usr/local/bin/mvim
> 2012-08-20 12:53:04,912 INFO  [org.formic.util.CommandExecutor] vim -f -X -u NONE -U NONE --cmd redir! > /var/folders/k9/k7gbksbs2d51dg4npcl_3fkm0000gn/T/eclim_installer8993806334309440888.tmp | silent! echo &rtp | quit
> 2012-08-20 12:53:30,192 INFO  [org.formic.util.CommandExecutor] vim --version
> 2012-08-20 12:53:31,869 INFO  [org.formic.util.CommandExecutor] java -Xmx256M -Dhttp.nonProxyHosts=local|_.local|169.254/16|_.169.254/16 -jar /Applications/Genuitec/Common/plugins/org.eclipse.equinox.launcher_1.3.0.v20120522-1813.jar -clean -application org.eclipse.equinox.p2.director -repository file:///var/folders/k9/k7gbksbs2d51dg4npcl_3fkm0000gn/T/formic_1595891067/update -installIU org.eclim.installer.feature.group
> 2012-08-20 12:53:33,273 WARN  [org.eclim.installer.step.EclipseInfo] Error installing eclim installer feature, attempting uninstall/reinstall.
> 2012-08-20 12:53:33,278 INFO  [org.formic.util.CommandExecutor] java -Xmx256M -Dhttp.nonProxyHosts=local|_.local|169.254/16|_.169.254/16 -jar /Applications/Genuitec/Common/plugins/org.eclipse.equinox.launcher_1.3.0.v20120522-1813.jar -clean -application org.eclipse.equinox.p2.director -repository file:///var/folders/k9/k7gbksbs2d51dg4npcl_3fkm0000gn/T/formic_1595891067/update -uninstallIU org.eclim.installer.feature.group
> 2012-08-20 12:53:34,774 INFO  [org.formic.util.CommandExecutor] java -Xmx256M -Dhttp.nonProxyHosts=local|_.local|169.254/16|_.169.254/16 -jar /Applications/Genuitec/Common/plugins/org.eclipse.equinox.launcher_1.3.0.v20120522-1813.jar -clean -application org.eclipse.equinox.p2.director -repository file:///var/folders/k9/k7gbksbs2d51dg4npcl_3fkm0000gn/T/formic_1595891067/update -installIU org.eclim.installer.feature.group
> java.lang.RuntimeException: error:  out: An error has occurred. See the log file
> /Applications/Genuitec/Common/configuration/1345460012623.log.
>   at org.eclim.installer.step.EclipseInfo.installInstallerPlugin(EclipseInfo.java:183)
>   at org.eclim.installer.step.EclipseInfoStep$1.run(EclipseInfoStep.java:67)
>   at foxtrot.AbstractWorkerThread$1.run(AbstractWorkerThread.java:40)
>   at java.security.AccessController.doPrivileged(Native Method)
>   at foxtrot.AbstractWorkerThread.runTask(AbstractWorkerThread.java:36)
>   at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:199)
>   at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:182)
>   at java.lang.Thread.run(Thread.java:722)
> Installer Context (Please include in bug reports):
>  eclipse.home=/Applications/Genuitec/Common
>  vim.files=/Users/dh/.vim/bundle/eclim
>  vim.skip=false

**Comment by rtyler** [comment]
On the current Eclipse [downloads](http://www.eclipse.org/downloads/) page the links at the top all link to the "New Eclipse Installer" which doesn't place the equinox launcher where eclim's installer expects it.

**Comment by sideshowbarker** [comment]
> On the current Eclipse downloads page the links at the top all link to the "New Eclipse Installer" which doesn't place the equinox launcher where eclim's installer expects it.

Yeah, it seems you need to give eclim the path to the `Eclipse.app/Contents/Eclipse` subdirectory in whatever directory you’ve installed Eclipse in.

FWIW, I’ve personally found it easier to skip trying to use both the official Eclipse installer and the eclim installer jar and instead just install Eclipse from [Homebrew Cask](http://caskroom.io/) and eclim from this repo; like this:

```
brew install ant
brew cask install eclipse-java
git clone git://github.com/ervandew/eclim.git
cd eclim
ant -Declipse.home=/opt/homebrew-cask/Caskroom/eclipse-java/4.5.1/Eclipse.app/Contents/Eclipse
```

**Comment by ervandew** [comment]
I'm closing this out since the new eclim command line installer should solve this.
