### ISSUE TITLE
[android] Missing required options on exec: CreateProject

### ISSUE THREAD

**Issue by chookies** [ervandew/eclim#240]
When I try to create a new android project with the following command:

	CreateProject ~/newproject -n android

The command returns the following error:

	Missing required options: target, package, application
	while executing command (port: 9091): -editor vim -command project_create "~/newproject" -n android

My guess is that the adt plugin has changed and requires more arguments now? Or is it something else?

**Comment by f4t-t0ny** [comment]
I had the same project (while using vim-eclim from here: https://github.com/dansomething/vim-eclim), apparently eclim didn't have the eclim directory in "runtimepath". So check if this directory is loaded for you. For me
```
set runtimepath+=~/.vim/bundle/vim-eclim/eclim
```
fixed it

**Comment by ervandew** [comment]
> I had the same project (while using vim-eclim from here: https://github.com/dansomething/vim-eclim)

I highly discourage using third-party repos like this that attempt to mirror just the eclim vim files. That repo is already out of date, so any bug fixes or changes made in 2.4.1 will be missing and unless you've installed every eclim plugin on the daemon side, that repo will include vim files for features you don't have installed.

> set runtimepath+=~/.vim/bundle/vim-eclim/eclim
> 
> in .vimrc fixed it

I also discourage recommending adding that to anyone's vimrc. The `pluing/eclim.vim` file will do that for you, and if it hasn't, then either something larger is wrong or your vim instance isn't fully compatible, so brute forcing your way past probably isn't the best approach.

**Comment by f4t-t0ny** [comment]
Hi ervandew, 

thanks for your comment, I'm glad someone explained that. It's just that i assumed this error is caused by this (unsupported, old) repository, and tried to fix it for myself :(

I just use it as i like keeping my complete vim configuration in my dotfiles repo, so it immediately works without installing anything manually. I mean i even suspected it's evil, but it sort of was the best alternative for me. 

Can't you create/provide an official repository for eclim's vim files?

**Comment by ervandew** [comment]
> Can't you create/provide an official repository for eclim's vim files?

Not really because I don't know what version of eclim people have installed. I imagine many users would end up with eclim vim files that are newer than the daemon version, resulting in lots of potential issues.

**Comment by f4t-t0ny** [comment]
Hi ervandew, 

Can i instead just import the repository into vundle with?
```
Plugin 'ervandew/eclim', {'rtp': 'org.eclim.core/vim'}
for eclim_plugin in ['adt', 'cdt', 'dltk', 'dltkruby', 'groovy', 'jdt', 'pdt', 
\ 'pydev', 'sdt', 'vimplugin', 'wst']
  exec 'set rtp+='.$HOME.'/.vim/bundle/eclim/'.'org.eclim.'.eclim_plugin.'/vim/eclim'
endfor
``` 
It work's with eclim, at least i didn't see anything bad breaking. 
Or is it even more evil, than the thing i did before?

**Comment by ervandew** [comment]
@f4t-t0ny 
What you have there is the same thing, just using eclim's repository instead of some third party. You could still end up with vim files that don't match the daemon version.

**Comment by alem0lars** [comment]
@ervandew Is it possible to put all of vim stuff into a single folder so we don't need dirty hacks (for runtimepath) to get eclim working?

**Comment by ervandew** [comment]
@alem0lars 
As discussed above, if you are using "dirty hacks", you are doing it wrong.
