### ISSUE TITLE
Simplify Install for Plugin Managers

### ISSUE THREAD

**Issue by starcraftman** [ervandew/eclim#378]
I manage my dotfiles directory and didn't really like eclim installing plugins into .vim/eclim and .vim/plugin. To fix this, I simply took the vim files and repackaged it with small modification into a plugin compatible layout. See https://github.com/starcraftman/vim-eclim .

With this, users who use managers like Vundle, Plug or even pathogen wouldn't have to manually install everywhere... It also makes global disable as easy as commenting.

i.e. For Vundle (in your vimrc).

```
Plugin 'starcraftman/vim-eclim'
```

As a side effect, you could remove half the install process as now we'd only need to install/upgrade the eclim instance installed to the eclipse folder. Or at least make it optional checkbox. Just a thought.

**Comment by starcraftman** [comment]
Heh forgot about this, too many notifications. Also haven't been using it this month.

@vheon I did want that originally, but I kept the eclim standard layout so a user could install over it directly copy/paste. Changing layout while better is more disruptive to this plugin.

@ervandew I understand those concerns. "This" solution I know didn't support all combinations, it was meant more as an inspiration, I made it quickly. The idea of vim commands that would do things like InstallEclim & UpgradeEclim were what I meant. The latter intelligently fetching based on your eclipse & vim directories. And the stale combination/versions definitely a serious issue. Though if you had a command to upgrade simultaneously to latest stable, that might actually reduce it. If I had the exact answer, I'd have made a PR. I'm not an eclim code expert.

I'll leave this open as I think it could be addressed, I'm just not the one likely to do it. 

@jsholmes Basically what I was getting at, hope it gets done.

**Comment by denzeljiang** [comment]
Hey guys, 

I created a clone [repo](https://github.com/denzeljiang/vim-eclim/commits/master) including all vim files(without doc files) from eclim. And the repo includes all tags and branches since [1.7.7.1](https://github.com/ervandew/eclim/tree/1.7.7.1).

I'm using that pretty smoothly. I definitely agree with what @ervandew said:

> not all of eclim's .vim files will be used by all users. 

It's gonna be a huge waste to load all .vim files. But I'm wondering that will including all vim files break any functionality of vim? If it wouldn't, I think personally I'm ok with having a little performance downside.

Thank you!

**Comment by justinmk** [comment]
>  but with eclim, you only want the .vim files for the features you have available in your eclipse/eclimd install. So your repo has the java vim files, but another user may just want the c vim files, another just the python vim files, yet another user may want the java and python vim files, and so on through all the possible permutations.

Why wouldn't this be solved by Vim's `autoload/` approach? What is the cost (other than disk space) of having all the eclim vim files? Eclim should only source files as needed from `autoload/`.

**Comment by ervandew** [comment]
What I would like to understand is: If you guys have to install the eclim daemon anyways, why do you want to install the vim files separately?

Installing both at the same time ensures that both are on the same version and are compatible with each other. Installing them separately can lead to all kinds of weird bugs that would presumably be tracked down to version mismatches.

**Comment by justinmk** [comment]
@ervandew One advantage of following the standard layout for vim plugins is that eclim can be enabled/disabled by plugin managers (e.g. https://github.com/junegunn/vim-plug ). The version of eclim that I have (about 1 year old), creates `.vim/plugin/eclim.vim` and if I recall, in order to disable it I had to actually move/delete that file.

(The reason I want to disable eclim for non-java projects, is that it is far too eager to manage my tabs, and it seems to pop up at other random undesired times, basically hanging around in the form of autocmds I did not bother to investigate. I only want it to exist for java trees, not python etc. 

That's a different discussion though...)

**Comment by rkannan82** [comment]
You could use the EclimDisable command for that.

**Comment by justinmk** [comment]
No, EclimDisable does basically nothing:

https://github.com/ervandew/eclim/blob/94ed0d6f075eaded1cd203e702bbc9ac31dca7ea/org.eclim.core/vim/eclim/autoload/eclim.vim#L173

All the autocmds, not to mention user-commands (`:EclimFoo`) are left in place.

**Comment by ervandew** [comment]
@justinmk 
>  creates `.vim/plugin/eclim.vim`

It does if you use the default install path, but you can easily change that path to `.vim/bundle/eclim` etc.  I'm not sure if any of the plugin manager (besides pathogen) can be used to just load bundles and not clone from git repositories.

> in order to disable it I had to actually move/delete that file.

If you use `let g:EclimDisabled = 1` then the only eclim command you will have is `:EclimValidate` and no autocmds will be created or any other eclim files sourced.

> The reason I want to disable eclim for non-java projects...

I'd love to get specifics on the issues you've run into in either another github issue or on one of the eclim mailing lists. The goal was to make eclim unobtrusive and unnoticeable when not working within an eclipse project, but it sounds like that goal has not been met in your case, so I would like to remedy that.

**Comment by ervandew** [comment]
>>    in order to disable it I had to actually move/delete that file.

> If you use `let g:EclimDisabled = 1` then the only eclim command you will have is :EclimValidate and no autocmds will be created or any other eclim files sourced.

I should clarify that setting that variable before `plugin/eclim.vim` is loaded (like in your vimrc), should get you the behavior you want. Setting it afterwards, like `:EclimDisable` does, pretty much just disables all communication with the daemon.

**Comment by justinmk** [comment]
@ervandew Thanks, I will take a deeper look in the next week or two and report what I find.

**Comment by enricobacis** [comment]
Hi, sorry to bump old threads, but is there any update on this issue?
