### ISSUE TITLE
v2.4.1 and Scala IDE 4.0.0

### ISSUE THREAD

**Issue by tlee** [ervandew/eclim#387]
I set this up last weekend on Scala IDE 4.0.0, but ran into some problems with running the installer from the jar.  I ran into a conflict during the install process installing the sdt feature dependency. 

https://github.com/ervandew/eclim/blob/1de73d8620f541bb376883be6973f16bf99cac41/org.eclim.installer/build/resources/dependencies.xml#L60

Pulling from dev caused a dependency conflict.  I changed the sdt feature dependency instead to the latest stable:

http://download.scala-ide.org/sdk/lithium/e44/scala211/stable/site

Repackaging the jar with this change - solved the dependency conflict.

Thanks a ton for the work here.  Look forward to putting it to use.

**Comment by ervandew** [comment]
Thanks for catching that and testing the change. I'll build a new release after I get a chance to look into some other possible issues.
