### ISSUE TITLE
Code completion in Vim/Neocomplete not working, any suggestions? 

### ISSUE THREAD

**Issue by ReneFroger** [ervandew/eclim#389]
Thanks for your awesome work. It's really appreciated. :+1: 
   Are you considering to accept donations, by the way?

  I have some problems to get this working.

Specs: Windows 7 x64, Java JRE, Eclipse Luna for PHP developers, and Vim 7.4.430 with Neocomplete (the successor to Neocomplcache) in my Path.  

 I installed Eclim. Started eclim.d bat.  

In Gvim, `:EclimValidate` says all settings are valid. 
`:PingEclim` gives me the message: Eclim 2.4.1 and Eclipse 4.4.0. 

`:ProjectList` gives me a project folder, that I created in Eclipse earlier. 

When I open a file in Gvim, inside the project folder of Eclipse, I get the default code completion from NeoComplete. Not the default completion that I get in Eclipse, when I open the same PHP file.

Accordingly to the manual for *Neocomplcache*, I assume this works the same way for Neocomplete, I put in my .vimrc: 
`let g:EclimCompletionMethod = 'omnifunc'`

I didn't include the following: 
>       if !exists('g:neocomplcache_force_omni_patterns')
>         let g:neocomplcache_force_omni_patterns = {}
 >      endif

 >    let g:neocomplcache_force_omni_patterns.java = '\k\.\k*'

Given the fact it's for PHP-files, and not Java. 

When I started Vim again, with the above setting in .vimrc, I see a message in the command line when I wait on code completion: 

`(1s) system: " "C:\Users\MyName\Desktop\eclipse\plugins\org.eclim_2.4.1\bin/eclim.bat" --nailgun-server localhost --nailgun-port 9091 -editor vim -command php_complete -p "test" -f "newfile.php" -o 51 -e utf-8`

But I couldn't get figure out what went wrong. I found no answer in troubleshooting. Keep in mind I use it for PHP files, not Java files. But the code completion in Eclipse for PHP files works usually fine.

Any suggestions in order to debug this? 

Thanks in advance for your reply!

**Comment by ervandew** [comment]
>    Thanks for your awesome work. It's really appreciated.
>    Are you considering to accept donations, by the way?

No, but other contributions[0] are welcome.

[0] http://eclim.org/contribute.html

>   I have some problems to get this working.
> 
> Specs: Windows 7 x64, Java JRE, Eclipse Luna for PHP developers, and Vim 7.4.430 with Neocomplete (the successor to Neocomplcache) in my Path.  
> 
>  I installed Eclim. Started eclim.d bat.  
> 
> In Gvim, `:EclimValidate` says all settings are valid. 
> `:PingEclim` gives me the message: Eclim 2.4.1 and Eclipse 4.4.0. 
> 
> `:ProjectList` gives me a project folder, that I created in Eclipse earlier. 
> 
> When I open a file in Gvim, inside the project folder of Eclipse, I get the default code completion from NeoComplete. Not the default completion that I get in Eclipse, when I open the same PHP file.
> 
> Accordingly to the manual for *Neocomplcache*, I assume this works the same way for Neocomplete, I put in my .vimrc: 
> `let g:EclimCompletionMethod = 'omnifunc'`
> 
> I didn't include the following: 
> `if !exists('g:neocomplcache_force_omni_patterns')
>   let g:neocomplcache_force_omni_patterns = {}
> endif
> let g:neocomplcache_force_omni_patterns.java = '\k\.\k*'`
> 
> Given the fact it's for PHP-files, and not Java. 
> 
> When I started Vim again, with the above setting in .vimrc, I get the message when I wait on code completion: 
> 
> "(1s) system: " "C:\Users\MyName\Desktop\eclipse\plugins\org.eclim_2.4.1\bin/eclim.bat" --nailgun-server localhost --nailgun-port 9091 -editor vim -command php_complete -p "test" -f "newfile.php" -o 51 -e utf-8"
> 
> But I couldn't get figure out what went wrong. I found no answer in troubleshooting. Keep in mind I use it for PHP files, not Java files. But the code completion in Eclipse for PHP files works usually fine.
> 
> Any suggestions in order to debug this? 

The first thing I would do is bypass neocomplete and ensure that you
can get eclim code completion working directly.  If you use
`<c-x><c-o>` do you get the expected completions?

**Comment by ReneFroger** [comment]
Hello Eric. 

Thanks for your reply, it's really appreciated. 

After I disabled Neocomplete, and I test `<c-x><c-o>`, I get the expected completions indeed. So I need to fix the Neocomplete. So Eclim is working fine here. You could consider this issue as closed. Thanks for your reply, and I like your effort for the Eclim project. 

Thanks for that!
