### ISSUE TITLE
Mvn3 - Does eclim support mvn3? How to import an existing project with mvn3?

### ISSUE THREAD

**Issue by mitermayer** [ervandew/eclim#393]
Trying to use eclim as the main development platform, and was wondering what are the current support for maven 3? Would like a way to load an existing project without having to go to eclipse GUI.

thanks,
Miter

**Comment by ervandew** [comment]
> what are the current support for maven 3?

Eclim doesn't have any specific support for maven 3.

> Would like a way to load an existing project without having to go to eclipse GUI.

If it's an existing eclipse project then you can use the `:ProjectImport` command. Otherwise you can create a new jave project normally, you'll just have to update your .classpath file to include all your projects dependencies.
