### ISSUE TITLE
Configure build path and resource filters

### ISSUE THREAD

**Issue by kminh** [ervandew/eclim#394]
Hello,

I'm trying to configure the build path for a PHP project as per http://eclim.org/vim/dltk/buildpath.html but it seems that none of the commands are available (built Eclim with Eclipse PDT).

Also, is there a way to edit resource filters through Eclim (i.e. http://help.eclipse.org/luna/index.jsp?topic=%2Forg.eclipse.platform.doc.user%2Fconcepts%2Fresourcefilters.htm?) Or do I have to edit  those via Eclipse's GUI?

Thank you.

**Comment by ervandew** [comment]
> I'm trying to configure the build path for a PHP project as per http://eclim.org/vim/dltk/buildpath.html but it seems that none of the commands are available (built Eclim with Eclipse PDT).

Are you currently editing your project's `.buildpath` file when attempting to execute those commands? What is the filetype reported by vim (`:verbose set ft?`) while editing that file?

> Also, is there a way to edit resource filters through Eclim

Unfortunately there isn't. You'll have to use the gui to set those up.

**Comment by kminh** [comment]
No I was editing some PHP files, the `.buildpath` file isn't even on the buffer list.

`:verbose set ft?` returns: 

```
filetype=eclipse_buildpath
Last set from ~/.vim/eclim/plugin/ftdetect.vim
```

None of the commands starting with `:New...` are there.

**Comment by ervandew** [comment]
Do you have filetype plugins enabled?

    :EclimValidate

**Comment by kminh** [comment]
Yes all working fine now, my mistake (did not read the documentation carefully enough).
