### ISSUE TITLE
Auto open/close project when Vim starts/closes

### ISSUE THREAD

**Issue by kminh** [ervandew/eclim#395]
Hi again,

Is it possible to auto open/close a project (only when it is a file in the project and the project has not been opened/closed?) I thought this is the default behaviour but it doesn't seem so.

If that's not available, can we make use of something like `eclim#project#util#IsCurrentFileInProject` to open/close project on `VimEnter/VimLeave` event?

Thanks.

**Comment by ervandew** [comment]
What you mean by open/close a project? Are you referring to opening/closing the project in eclipse, opening/closing the project tree in eclim?

**Comment by kminh** [comment]
I mean can Eclim execute `:ProjectOpen` when we start vim and then execute `:ProjectClose` when we close vim? (right now all of my projects still stay opened when I quit vim).

**Comment by ervandew** [comment]
I think that feature is outside the scope of eclim. Eclim will auto open closed projects when certain features that require the project to be open are executed. Closing the project however seems like something that should be handled by a user defined autocmd.

**Comment by kminh** [comment]
Ok, let's close this until someone else wants the same feature :)
