### ISSUE TITLE
eclimd fails to start - unable to load class org.eclipse.ui.internal.ide.misc.FileInfoAttributesMatcher

### ISSUE THREAD

**Issue by kminh** [ervandew/eclim#396]
Eclim has been working nicely for a couple of weeks but suddenly I'm receiving this error when starting eclimd:

```
/usr/bin/java -version
java version "1.7.0_75"
OpenJDK Runtime Environment (IcedTea 2.5.4) (Arch Linux build 7.u75_2.5.4-1-x86_64)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)

/usr/bin/java -d64 -Dosgi.requiredJavaVersion=1.7 -XX:MaxPermSize=256m -Xms40m -Xmx512m -jar /usr/share/eclipse//plugins/org.eclipse.equinox.launcher_1.3.0.v20140415-2008.jar -debug -clean -refresh -application org.eclim.application
Install location:
    file:/usr/share/eclipse/
Configuration file:
    file:/usr/share/eclipse/configuration/config.ini loaded
Configuration location:
    file:/home/user/.eclipse/org.eclipse.platform_4.4.2_1543616141_linux_gtk_x86_64/configuration/
Configuration file:
    file:/home/user/.eclipse/org.eclipse.platform_4.4.2_1543616141_linux_gtk_x86_64/configuration/config.ini loaded
Loading timestamp file from:
	 file:/home/user/.eclipse/org.eclipse.platform_4.4.2_1543616141_linux_gtk_x86_64/configuration/   .baseConfigIniTimestamp
Timestamps found: 
	 config.ini in the base: 1424336656000
	 remembered 1424336656000
Shared configuration location:
    file:/usr/share/eclipse/configuration/
Framework located:
    file:/usr/share/eclipse/plugins/org.eclipse.osgi_3.10.2.v20150203-1939.jar
Loading extension: reference:file:org.eclipse.osgi.compatibility.state_1.0.1.v20140709-1414.jar
	eclipse.properties not found
Framework classpath:
    file:/usr/share/eclipse/plugins/org.eclipse.osgi_3.10.2.v20150203-1939.jar
    file:/usr/share/eclipse/plugins/
    file:/usr/share/eclipse/plugins/org.eclipse.osgi.compatibility.state_1.0.1.v20140709-1414.jar
Debug options:
    file:/home/user/.options not found
Time to load bundles: 53
Starting application: 12339
org.eclipse.core.runtime.CoreException: Plug-in org.eclipse.ui.ide was unable to load class org.eclipse.ui.internal.ide.misc.FileInfoAttributesMatcher.
```

I'm launching eclimd via a symlink (`~/.eclipse/eclimd` which points to `/home/user/.eclipse/org.eclipse.platform_4.4.2_1543616141_linux_gtk_x86_64/eclimd`).

Before, to start eclimd I manually ran `~/.eclipse/eclimd` and have never encountered the above issue. Now to autostart eclimd when I login I put this into my `.xprofile`:

```bash
/home/user/.eclipse/eclimd -b & (not sure if -b is needed here)
```

After some successful autostart now the autostart doesn't work anymore and when I try to manually start eclimd I encounter such issue.

The full trace is quite long so I will post if needed.

Thank you.

**Comment by ervandew** [comment]
Are you able to start the eclipse gui?
Can you start eclimd against a new workspace?

Can you also post the full stack trace. A lot of times the exception at the top is a red herring and the root cause is much further down.

**Comment by kminh** [comment]
I can start eclimd again by removing some `.snap` file in workspace/.metadata/.plugins/, and against a new workspace, but that seems to clear the project list. I can start the GUI normally.

It seems that if I try to read the project from Eclipse GUI (to modify some settings that Eclim doesn't provide) it will cause an issue the next time you start eclimd. One possible way to reproduce is:

- Start eclimd using `.xprofile` with above commands
- Start vim and create some projects
- Close eclimd either using shutdown command or just Ctrl-C
- Start Eclipse GUI to browse just created projects and change setting, do some file edits etc.
- Close Eclipse GUI and restart eclimd

Actually the only reason I ever have to open Eclipse GUI is to exclude certain folder, I just don't know the syntax for `.buildpath` file to exclude folders (perhaps there should be a command in Vim?).

I have unfortunately removed the full stack trace, sorry.

**Comment by kminh** [comment]
Been awhile since I encountered this issue, so closing now.
