### ISSUE TITLE
Support for Eclipse 4.5

### ISSUE THREAD

**Issue by quicknir** [ervandew/eclim#407]
Currently, eclim does not support Eclipse 4.5. Would be great if it did.

**Comment by ervandew** [comment]
There is a 'mars' branch where eclim will at least compile. Many unit tests failures though and suppressing the main window when running in headless mode stopped working for some reason.

I'm not sure when I'll have the time to dig in and fix all these issues, so any help would be much appreciated.

**Comment by egorchik007** [comment]
I would love the 4.5-eclipse-ready version of eclim, too.

**Comment by razamatan** [comment]
@ervandew any list of open issues for stabilizing 4.5 to reference to start helping out?

**Comment by partheinstein** [comment]
Just a FYI.

When I run start-eclimd with eclipse4.5, eclipse UI starts up and gives me a popup window that says "setup check failed". It complains that eclipse.launcher property is not set.

**Comment by SeanFelipe** [comment]
from the perspective of an eclim user, what's interesting about eclipse 4.5? I see idea + Android Studio grabbing most of the attention these days. I still want to use eclipse + eclim, but I do see everybody switching to IDEA.

**Comment by ervandew** [comment]
The `master` branch now supports eclipse 4.5 (mars).
