### ISSUE TITLE
vim command :Mvn test doesn't fill quickfix list

### ISSUE THREAD

**Issue by zimnyx** [ervandew/eclim#408]
Hi! I got maven project with failing unit test. http://eclim.org/vim/java/maven.html suggest that :Mvn command shlould fill quickfix list with junit errors, but after running ":Mvn test" doesn't fill the quickfix list with failed tests.

**Comment by ervandew** [comment]
Does your maven output differ from the default?

I would need some example output to diagnose.

**Comment by zimnyx** [comment]
I think problem occurs when during test some output is emited:
```
Running com.mycompany.app.AppTest
Some output or logging here
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.066 sec <<< FAILURE!
```
I've noticed that when any output is emitted between "Running ..." and "Test run", :Mvn command doesn't see test failure.

**Comment by ervandew** [comment]
Ah, that makes sense.

In the directory where you installed the eclim vim files, edit the file `eclim/compiler/eclim_mvn.vim` and try changing the `exec CompilerSet errorformat=` block to:

    exec 'CompilerSet errorformat=' .
      \ '\%A%f:[%l\\,%c]\ %m,' .
      \ '\%Csymbol%.%#:\ %m,' .
      \ '\%Zlocation%.%#:\ %m,' .
      \ '\%AEmbedded\ error:%.%#\ -\ %f:%l:\ %m,' .
      \ '\%-Z\ %p^,' .
      \ '\%A%f:%l:\ %m,' .
      \ '\%-Z\ %p^,' .
      \ '\%ARunning\ %f,' .
      \ '\%+ZTests\ run%.%#FAILURE!,' .
      \ '\%ARunning\ %f,' .
      \ '\%C%.%#,' .
      \ '\%+ZTests\ run%.%#FAILURE!,' .
      \ g:EclimMvnCompilerAdditionalErrorFormat .
      \ '\%-G%.%#'

Then restart your vim instance and trying running `:Mvn test` again.

I don't have any maven tests setup, so I tested this using `cfile`, but before I commit it, I'd like you to give a shot against some actual unit tests.

**Comment by zimnyx** [comment]
Hey!
It still doesn;t work with such output:
```
Running com.company.pi.ds.zzz.CellConfigurationFactoryTest
09:13:42.421 [main] INFO  c.c.p.d.c.CellConfigurationFactory - Foo bar.
09:13:42.425 [main] INFO  c.c.p.d.c.CellConfigurationFactory - fooo bar
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.068 sec <<< FAILURE! - in com.company.pi.ds.zzz.CellConfigurationFactoryTest
```

**Comment by ervandew** [comment]
See if this does the trick:

    exec 'CompilerSet errorformat=' .
      \ '\%A%f:[%l\\,%c]\ %m,' .
      \ '\%Csymbol%.%#:\ %m,' .
      \ '\%Zlocation%.%#:\ %m,' .
      \ '\%AEmbedded\ error:%.%#\ -\ %f:%l:\ %m,' .
      \ '\%-Z\ %p^,' .
      \ '\%A%f:%l:\ %m,' .
      \ '\%-Z\ %p^,' .
      \ '\%ARunning\ %f,' .
      \ '\%+ZTests\ run%.%#FAILURE!%.%#,' .
      \ '\%ARunning\ %f,' .
      \ '\%C%.%#,' .
      \ '\%+ZTests\ run%.%#FAILURE!%.%#,' .
      \ g:EclimMvnCompilerAdditionalErrorFormat .
      \ '\%-G%.%#'

**Comment by zimnyx** [comment]
Eric, I cannot reproduce it now. I'll try using :Junit for a few days, and we'll see if problem occurs.

**Comment by ervandew** [comment]
Does that mean the update pattern I posted works as intended for you?
