### ISSUE TITLE
Error: The project description file is missing

### ISSUE THREAD

**Issue by alem0lars** [ervandew/eclim#409]
When I try to create a new project (using: `:ProjectCreate myapp -n android` and answering the prompted questions), I get the following error:

````
2015-07-10 08:19:33,849 INFO  [org.eclim.eclipse.EclimDaemon] Jobs finished.
2015-07-10 08:19:33,849 INFO  [org.eclim.eclipse.EclimDaemon] Eclim Server Started on: 127.0.0.1:9091
2015-07-10 08:23:00,636 ERROR [org.eclim.command.Main] Command failed
org.eclipse.core.internal.resources.ResourceException: The project description file (.project) for 'myapp' is missing.  This file contains important information about the project.  The project will not function properly until this file is restored.
        at org.eclipse.core.internal.localstore.FileSystemResourceManager.read(FileSystemResourceManager.java:851)
        at org.eclipse.core.internal.resources.SaveManager.restoreMetaInfo(SaveManager.java:884)
        at org.eclipse.core.internal.resources.SaveManager.restore(SaveManager.java:754)
        at org.eclipse.core.internal.resources.Project.open(Project.java:1129)
        at org.eclipse.core.internal.resources.Project.open(Project.java:1178)
        at org.eclim.plugin.core.util.ProjectUtils.getProject(ProjectUtils.java:149)
        at org.eclim.plugin.core.project.ProjectManagement.createProject(ProjectManagement.java:198)
        at org.eclim.plugin.core.project.ProjectManagement.create(ProjectManagement.java:164)
        at org.eclim.plugin.core.command.project.ProjectCreateCommand.execute(ProjectCreateCommand.java:68)
        at org.eclim.command.Main$1.run(Main.java:100)
        at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:136)
        at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3774)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3412)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$9.run(PartRenderingEngine.java:1151)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
        at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1032)
        at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:148)
        at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:636)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:579)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:135)
        at org.eclim.eclipse.EclimApplication.start(EclimApplication.java:124)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:648)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:603)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
NGSession 2: 127.0.0.1: org.eclim.command.Main exited with status 1
```

**Comment by ervandew** [comment]
What version of eclispe are you using?
What version of eclim are you using?
What version of adt are you using?
Did the `myapp` directory already exist?

I couldn't reproduce this issue simply using `:ProjectCreate myapp -n android` where `myapp` didn't exist. Can you provide a comprehensive list of steps including anything you may have done to pre-create `myapp` outside of eclim/eclipse?

**Comment by ervandew** [comment]
I should also note that based on your comment on #240 just before creating this issue, I'm a bit sceptical that you have a proper eclim installation. How did you install the eclim vim files and what "dirty hacks" did you use?

**Comment by alem0lars** [comment]
I'm using this configuration:

```
NeoBundle 'ervandew/eclim', {
      \   'rtp': 'org.eclim.core/vim',
      \ }

for eclim_plugin in [
      \ 'adt', 'cdt', 'dltk', 'dltkruby', 'groovy', 'jdt', 'pdt',
      \ 'pydev', 'sdt', 'vimplugin', 'wst']
  exe 'set runtimepath+=' .
        \ expand('<%= get_var! "vim.bundle_dir" %>') .
        \ '/eclim/org.eclim.' . eclim_plugin . '/vim/eclim'
endfor
```

When I've said dirty hacks I meant that I had to manually update the runtime path. However, this shouldn't have anything to do with this bug.

My relevant vim configuration is pretty much that. Eclim installation is correct since *I'm directly using your repository* (no external ones).

**Comment by ervandew** [comment]
> When I've said dirty hacks I meant that I had to manually update the runtime path (see code above)

You shouldn't be doing any of that, and doing so is not supported. By doing it that way you leave yourself open for mismatched version of code, where your vim files are more up to date than your eclim daemon code. Seeing this type of thing makes me think I need to add failures to various files that are only removed during the build process.

> The steps are pretty simple:

So far I can't reproduce the error. Again, does `myapp` already exist when you perform those steps? What version of adt are you using? Can you create the project from the eclipse gui?

**Comment by alem0lars** [comment]
> You shouldn't be doing any of that, and doing so is not supported. By doing it that way you leave yourself open for mismatched version of code, where your vim files are more up to date than your eclim daemon code. Seeing this type of thing makes me think I need to add failures to various files that are only removed during the build process.

These days, any person in this world uses plugins managers to manage their plugins in vim. There are a lot of solutions like neobundle, vundle, pathogen, etc..

This is because like every person in the earth using vim likes to use a plugin manager. The way you provide this plugin breaks the existing ecosystem, since installing it with the installer makes the vim folder dirty with manually installed eclim files and the only solution I've found so far using *all of your splitted vim files* (without relying on 3party vim eclim plugins) is to include your github repository and manually fix the runtime path.

Also, **this doesn't have anything to do with the issue** since the runtime path is correct and it includes all of the vim stuff.

> So far I can't reproduce the error. Again, does myapp already exist when you perform those steps? What version of adt are you using? Can you create the project from the eclipse gui?

Yes, I can create the project from the Eclipse gui. If I do that, then I can open the project with `:ProjectOpen` inside vim.

**Comment by alem0lars** [comment]
Plus, directly using your repository makes **impossible** to have mismatched versions of code between the daemon and the vim plugin.

**Comment by ervandew** [comment]
> These days, any person in this world uses plugins managers to manage their plugins in vim. There are a lot of solutions like neobundle, vundle, pathogen, etc..
>
> This is because like every person in the earth using vim likes to use a plugin manager. The way you provide this plugin breaks the existing ecosystem, since installing it with the installer makes the vim folder dirty with manually installed eclim files and the only solution I've found so far using all of your splitted vim files (without relying on 3party vim eclim plugins) is to include your github repository and manually fix the runtime path.

If eclim was like every other vim plugin, I would agree with you completely, but unfortunately it's not. It relies on the installation of plugins into a third party application using that application's plugin installation capabilities. A mismatch between blindly pulling in the eclim vim files from github and the lack of, or version mismatch, of the eclipse plugins means you're going to have problems eventually, and I'm stuck trying to unravel why. Installing both side in unison is the only sure fire way to ensure you don't have those kinds of problems, and neobundle, etc aren't going to be able to do that for you.

> Plus, directly using your repository makes impossible to have mismatched versions of code between the daemon and the vim plugin.

It's very possible since a) I highly doubt you have correct eclipse plugins installed for all the eclim plugins you are looping over in your snippet above and b) even if you did, and built them from the same version that you're eclim vim files came from, you are one update away from getting version mismatches since the vim files could be pulled in by neobundle without forcing you to re-build/install the updated eclim daemon plugins to support those new files. These aren't just theories either. I've dealt with people who have run into these issues doing it your way, and it's a waste of my time to figure out what happened.

>  Again, does myapp already exist when you perform those steps? What version of adt are you using?

^ perhaps the 3rd time is the charm? answers to these?

**Comment by alem0lars** [comment]
> It's very possible since a) I highly doubt you have correct eclipse plugins installed for all the eclim plugins you are looping over in your snippet above and b) even if you did, and built them from the same version that you're eclim vim files came from, you are one update away from getting version mismatches since the vim files could be pulled in by neobundle without forcing you to re-build/install the updated eclim daemon plugins to support those new files. These aren't just theories either. I've dealt with people who have run into these issues doing it your way, and it's a waste of my time to figure out what happened.

This can be solved by properly using git tags and don't use the code from HEAD but from the 2.4.1 tag.
Looping is bad, but (1) pragmatically does the same stuff you are doing since copying files with the installer or with a plugin manager does the same operations (2) can you suggest me a better way to do this (using a plugin manager)?

> does myapp already exist when you perform those steps?

No, obviously.

> What version of adt are you using?

The one installed with the eclim installer (run with `java -jar eclim-2.4.1.jar`), which is: `23.0.6.1720515`

**Comment by ervandew** [comment]
> This can be solved by properly using git tags and don't use the code from HEAD but from the 2.4.1 tag.

It still doesn't guarentee that you built the daemon code from that tag, just that you are using the vim sources from that tag.

> Looping is bad, but (1) pragmatically does the same stuff you are doing since copying files with the installer or with a plugin manager does the same operations

The difference with the installer is that it only installs what you need and it ensures that both the daemon side and vim side are using the same version.

> (2) can you suggest me a better way to do this (using a plugin manager)?

Install eclim using the gui installer or from the source and set the target vimfiles directory to `~/.vim/bundle/eclim`, then tell your plugin manager to use that instead of pulling directly from git.

> No, obviously.

It's not obvious. You could have an empty `myapp` dir, you could have used someother tool (maven, android create project ..., etc) to initialize a project. I'm not sitting at your computer, so it's certainly not obvious to me.

**Comment by alem0lars** [comment]
> The difference with the installer is that it only installs what you need
and it ensures that both the daemon side and vim side are using the same
version.

Again... You are making a statement which is clearly correct (I need to
have the same version) but you motivate it with insufficient reasons (use
the installer).

If I install the daemon using the installer (version 2.4.1) and the vim
plugin without the installer but with tag 2.4.1 it has to be the same
version since **it is the same version**.

----

> Install eclim using the gui installer or from the source and set the
target vimfiles directory to ~/.vim/bundle/eclim, then tell your plugin
manager to use that instead of pulling directly from git.

I use a systemwide vim configuration (i.e. in /etc/vim) but I cannot
install it as root (idk why, but eclim gives error when trying to install
it systemwide, i.e. as root).

Thus, I am forced to install eclim for a single normal user. This prevents
me to install the vim plugin using the installer (it requires root
permission).
This prevents me to do "in your way" cuz you're saying I am forced to
install vim plugin using installer but I can't because your installer
requires to be non-root.

Your installation option is actually impossible to be respected to me. Or
you fix the plugin stuff (making it like any other plugin in the earth) or
you fix the permissions problems (also, consider eclipse normally let you
install systemwide plugins, but you're preventing this to be systemwide,
why?) or you provide a third way which isn't impossible to be used.

----

> It's not obvious. You could have an empty myapp dir, you could have used
someother tool (maven, android create project ..., etc) to initialize a
project. I'm not sitting at your computer, so it's certainly not obvious to
me.

What it was obvious is I've tried all of the ways (with existing dir and
with non-existing dir) before reporting the issue.

----

And again, for the last time, this is not an issue about your packaging
policy or whatever you like. I've just reported an issue about an error
using :ProjectCreate and you are wasting my time complaining with me
because in other bugs people are complaining about your packaging
invention. I don't care about that here. If you want to discuss (and not
impose) about how to package stuff in vim, I'm glad to help you, but in
another issue and without antifeatures intimidations.

In any case, please stop talking about packaging policies here.

If you want to help fixing the ProjectCreate bug I'm here to test changes,
otherwise feel free to close this bug with "won't fix".

Thanks.

This can be solved by properly using git tags and don't use the code from
HEAD but from the 2.4.1 tag.

It still doesn't guarentee that you built the daemon code from that tag,
just that you are using the vim sources from that tag.

Looping is bad, but (1) pragmatically does the same stuff you are doing
since copying files with the installer or with a plugin manager does the
same operations

The difference with the installer is that it only installs what you need
and it ensures that both the daemon side and vim side are using the same
version.

(2) can you suggest me a better way to do this (using a plugin manager)?

Install eclim using the gui installer or from the source and set the target
vimfiles directory to ~/.vim/bundle/eclim, then tell your plugin manager to
use that instead of pulling directly from git.

No, obviously.

It's not obvious. You could have an empty myapp dir, you could have used
someother tool (maven, android create project ..., etc) to initialize a
project. I'm not sitting at your computer, so it's certainly not obvious to
me.

—
Reply to this email directly or view it on GitHub
<https://github.com/ervandew/eclim/issues/409#issuecomment-120661437>.

**Comment by ervandew** [comment]
After installing matching eclipse and adt versions as you've specified here, I'm still unable to reproduce the problem.

Can you provide what values you supplied to the prompts when attempting to create that project? My only other guess at this point is that perhaps some value there has an affect.

Here is what I tested (where my working directory :

    :ProjectCreate myapp -n android
    Please specify a package name: org.myapp
    Please specify a name for this application: MyApp
    Is this a library project?
    (y/n): n
    Create an activity?
    (y/n): y
    Please specify an activity name: MyAppActivity

Another possibility could be the directory you are in when creating the project. Are you creating the project in your workspace, outside your workspace, as a nested project?

**Comment by ervandew** [comment]
> Your installation option is actually impossible to be respected to me. Or you fix the plugin stuff (making it like any other plugin in the earth) 

I don't know how many times I can say it. eclim isn't like other plugins, so doing it your way is just a bad idea.  I obviously can't force you to do anything. All I can do is decide to not support you should I even suspect the issue is a result of your chosen installation.

> What it was obvious is I've tried all of the ways (with existing dir and with non-existing dir) before reporting the issue.

How would this possibly be obvious? Until now you haven't mentioned any of that.

Despite my strong dislike of your chosen installation decisions, surely you can see I'm still trying to help you diagnose this issue, since I do agree that it's probably not related to how you load the eclim vim files. However, if my asking questions is going to result in snarky "obviously" responses, then I'll just spend my time doing something else.

**Comment by alem0lars** [comment]
> Another possibility could be the directory you are in when creating the project. Are you creating the project in your workspace, outside your workspace, as a nested project?

You are right, creating the project inside the namespace solves the problem.
Thanks :+1: 

However, it's possible (using the GUI) to create the project outside the workspace. Are you interested in supporting this?

I think we can consider the issue as closed (if the note above isn't already implemented). In this case, I would add a side note in the readme to tell this to users.

**Comment by ervandew** [comment]
So far I'm still unable to reproduce the issue even when creating the project outside of the workspace. Do you mind sharing the path to the parent directory that results in the failure? Or perhaps there is something else of significance regarding the parent directory (symlink, network mount, etc)?

**Comment by d8sasi** [comment]
I also got the Same Issue in Eclipse but the real problem is i removed the actual Source project folder from source location (from which eclipse is trying to take the project) to some other place hence my eclipse is unable to get web.xml file since it is not available. Now i changed my source project folder location to the path where eclipse is trying to search for. Issue Resolved for me.
