### ISSUE TITLE
Errors compiling pydev with eclipse 4.5

### ISSUE THREAD

**Issue by has207** [ervandew/eclim#412]
[javac] Compiling 10 source files to /home/herman/eclim/build/temp/classes/org.eclim.pydev
    [javac] /home/herman/eclim/org.eclim.pydev/java/org/eclim/plugin/pydev/command/complete/CodeCompleteCommand.java:189: error: method does not override or implement a method from a supertype
    [javac]     @Override
    [javac]     ^
    [javac] /home/herman/eclim/org.eclim.pydev/java/org/eclim/plugin/pydev/command/src/SrcUpdateCommand.java:118: error: constructor AnalysisPreferences in class AnalysisPreferences cannot be applied to given types;
    [javac]       IAnalysisPreferences analysisPreferences = new AnalysisPreferences(ifile);
    [javac]                                                  ^
    [javac]   required: no arguments
    [javac]   found: IFile
    [javac]   reason: actual and formal argument lists differ in length
    [javac] /home/herman/eclim/org.eclim.pydev/java/org/eclim/plugin/pydev/command/src/SrcUpdateCommand.java:119: error: method get in class DefaultIndentPrefs cannot be applied to given types;
    [javac]       IIndentPrefs indentPrefs = DefaultIndentPrefs.get(ifile);
    [javac]                                                    ^
    [javac]   required: no arguments
    [javac]   found: IFile
    [javac]   reason: actual and formal argument lists differ in length
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 3 errors

**Comment by ervandew** [comment]
Sounds like you have an old version of pydev. Try upgrading to pydev 4.2.0. If that still doesn't do the trick, then try running the eclipse garbage collector:

$ cd <eclim_src_root>
$ ant eclipse.gc

**Comment by has207** [comment]
That would explain it, got company-installed PyDev 3.9 here. I hammered it in by just removing PyDev since I don't actually need to use it. Thanks!
