### ISSUE TITLE
Completion do not work for multimodule maven

### ISSUE THREAD

**Issue by kleewho** [ervandew/eclim#417]
Consider multimodule maven project where the parent that contains other project is just `pom`. Completion in each of the submodule will depend on the alphabetical order of parent and submodule. For example if the parent project is named: `eclim-mvn` and the submodule is called `lib-a` then `eclim-mvn` will be returned as project from `ProjectByResource.java` and no completion will be possible as project doesn't have `java` nature.

On the other hand if parent is named `zeclim-mvn` and the submodule `lib-a` everything works fine.

Steps to reproduce both cases:
- Import https://github.com/kleewho/eclim-test-mvn-project/ to eclipse including all 4 projects
- Call 
```
./eclim -command project_by_resource -f /<path-to-project>/eclim-test-mvn-project/lib-a/src/main/java/com/acme/liba/LibraryA.java
```

- Use project returned from step before and call:
```
./eclim -command java_complete -p <project> -f lib-a/src/main/java/com/acme/liba/LibraryA.java -e iso-8859-1 -l standard -o 594
```
- Delete projects from workspace
- Rename main project from `eclim-mvn` to `zeclim-mvn`
- Reimport all 4 projects
- Call 
```
./eclim -command project_by_resource -f /<path-to-project>/eclim-test-mvn-project/lib-a/src/main/java/com/acme/liba/LibraryA.java
```

- Use project returned from step before and call:
```
./eclim -command java_complete -p <project> -f src/main/java/com/acme/liba/LibraryA.java -e iso-8859-1 -l standard -o 594
```

**Comment by kleewho** [comment]
Forgot to write that https://github.com/ervandew/eclim/blob/e91dcb482d3024a233ce6a212e16ea8ad1209d50/org.eclim.core/java/org/eclim/plugin/core/command/project/ProjectByResource.java#L60 here's the _faulty_ line

**Comment by ervandew** [comment]
just committed a fix that should do the trick, but let me know if it doesn't
