### ISSUE TITLE
j2ee with eclim

### ISSUE THREAD

**Issue by 7belrhalmia** [ervandew/eclim#420]
how to create a dynamic web project with eclim

**Comment by ervandew** [comment]
eclim doesn't have any specific j2ee features.

**Comment by 7belrhalmia** [comment]
@ervandew  we cannot devellop a j2ee application with eclim

**Comment by ervandew** [comment]
ultimately a j2ee app is just a java app with j2ee libs, so you can write code with eclim like any other java app. You may want to create your project from the eclipse gui though since they probably have one or more classpath containers they'll add to your project.

**Comment by 7belrhalmia** [comment]
@ervandew  when i create the project with eclipse and add necessery librairies i will imported into vim by :ProjectImport   so when i do that do i must indicate that to eclim in the .classpath and for the file of configurations like log4.proprities how can i manage that

**Comment by ervandew** [comment]
An eclim project == an eclipse project. If the project exists in eclipse then there is not need to use `:ProjectImport`.

**Comment by 7belrhalmia** [comment]
@ervandew  one last qquestion for the tomcate serveur how do i usit with eclim

**Comment by ervandew** [comment]
you could run one externally or you could run eclimd in the eclipse gui and run whatever tomcat support they have there.

**Comment by 7belrhalmia** [comment]
@ervandew  we can run eclim in eclipse
how we do that

**Comment by ervandew** [comment]
http://eclim.org/eclimd.html#headed-eclipse-server

**Comment by 7belrhalmia** [comment]
ah so now i will run tomcate inside eclipse and eclimd and when i will do :Java % in eclim it will auto detecte tomcate

**Comment by ervandew** [comment]
Eclim's `:Java` command simply runs your project's main class in a jvm, it doesn't have any knowledge of tomcat, etc.  If you want to run your code in tomcat, you'll need to use the eclipse tools, or do so outside of the ide (like you would if you didn't have an ide at all).
