### ISSUE TITLE
echodoc with eclim for java file

### ISSUE THREAD

**Issue by 7belrhalmia** [ervandew/eclim#422]
shugos hase develloped a wonderful plugin for neocomplete it show function info in vim info  but shugo tell me that eclim dosn't support vim info   https://github.com/Shougo/echodoc.vim/issues/9

**Comment by ervandew** [comment]
If you are wanting the javadocs in the completion info, then that is omitted because it can severly affect performance. I suggested an improvement[0] to vim many years ago which would allow me to include the javadoc info, but as it stands, that info can't be added without bring completions to a painful crawl.

[0] http://vim.1045645.n5.nabble.com/Code-completion-suggestions-td1198302.html

**Comment by 7belrhalmia** [comment]
so why when eclim suggest the function with the peramettre it not insert the function with the paramettre in visuel mode  so it will insert all the sunction like obj.function(String a,int z)  and String a is in visuel mode to change it and when we presse tab we move to int z

**Comment by ervandew** [comment]
Not sure I totally understood all that, but eclim's code completion does not insert parameters.

**Comment by 7belrhalmia** [comment]
yeah i understand the preview window of vim is nustty and when you insert the function youget like this       obj.function(             so if the function hase a lot of paramettre you will forgot them      there is no solution for that i hope it will be with neovim

**Comment by 7belrhalmia** [comment]
@ervandew  what a solution you do to get function paramettre hint

**Comment by ervandew** [comment]
If you enable the preview window in vim:

    set completeopt+=preview

Then that will be populated with the method's signature and, unless some other plugin is closing it, that preview window will stay open after the completion for your reference.

You can also use eclim's `:JavaDocPreview`  on classes, methods, etc to view the full javadoc of that element in text form (if the javadocs are available).
