### ISSUE TITLE
Markdown Errors appear when used with vim-plug

### ISSUE THREAD

**Issue by matthewfranglen** [ervandew/eclim#425]
### Steps to Reproduce

* Install vim 7.4.764

* Using the .vimrc:

```vimrc
silent !mkdir --parents ~/.vim/autoload
silent !curl --fail --location --output ~/.vim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

call plug#begin('~/.vim/plugged')
call plug#end()
```

* Install eclim 2.4.1

* Open the following file named README.md:

```markdown
A Sample File
=============
```

* Save the file with `:w`

### Expected Results

No errors.

### Actual Results

The first line of the file is highlighted and the following message appears in the statusline:
```
loc - (1 of 1): plain text isn't allowed in <head> elements
```

**Comment by matthewfranglen** [comment]
I don't know which plugin is responsible for the errors so I have opened this against vim-plug too: https://github.com/junegunn/vim-plug/issues/269

**Comment by ervandew** [comment]
Looks like the markdown ftplugin sources all html ftplugins as well.

Quick fix for now would be to add the following to your vimrc or some other file sourced when you edit a markdown file:

    let g:EclimHtmlValidate = 0

**Comment by matthewfranglen** [comment]
Excellent thank you.
