### ISSUE TITLE
  eclim error with fugitive plugin's :Gpush still problem

### ISSUE THREAD

**Issue by raspine** [ervandew/eclim#427]
I'm having problems with this #342 with eclim v2.5.0

**Comment by ervandew** [comment]
So far I can't reproduce the issue described in #342. Can you provide the full error along with any other relevant info?

**Comment by WilliamLightner** [comment]
The site wouldn't let me attach it to the issue.


Thanks, 

William Lightner | Sr Programming Specialist | Dual Data Center - East 

4793617540 (O) | 479-619-6018 (C) 
J.B. Hunt Transport, Inc. | What's your next move?™ 
Single Source | Intermodal | Dedicated | Final Mile | Truckload | LTL | 
Refrigerated | Flatbed

**Comment by raspine** [comment]
This is what I'm getting when doing Gpush (I'm a new eclime user so maybe I'm missing something for setting it up but everything else seems to work fine):

Error detected while processing function <SNR>34_Dispatch..ecli#util#Make..eclim#util#MakeWithCompiler:
line 64:
E666: compiler not supported: git

**Comment by ervandew** [comment]
do you have vim-dispatch installed?

**Comment by raspine** [comment]
No, only Fugitive

**Comment by ervandew** [comment]
i figured that was the case and could reproduce after removing dispatch from the equation. My commit a few hours ago should resolve the problem, but let me know if it doesn't.

**Comment by raspine** [comment]
Works thanks!
