### ISSUE TITLE
Install bugs on OS X 10.10.4

### ISSUE THREAD

**Issue by z3t0** [ervandew/eclim#428]
Java JDK: 1.8
OS: OSX Yosemite 10.10.4
The installer for version 2.5.0 is buggy and the text when choosing directories for vim and eclipse is not visible.

**Comment by ervandew** [comment]
> The installer for version 2.5.0 is buggy

Can you elaborate on that, or is it just file chooser display issues?

**Comment by mn-green** [comment]
Probably, I happened the same situation.
I cannot choose Eclipse Home.
But I can choose Eclipse ver 4.4.2(It cannot pass in Requirements).
It may be occurred by changing a directory structure. 
In OS X, the directory structure of Eclipse under version 4.5 is below.
![image](https://cloud.githubusercontent.com/assets/13245874/9871366/2afb3980-5bce-11e5-8e12-60104de6527b.png)
But Eclipse of version 4.5 unifies Eclipse.app in OS X(its image is below).
![image](https://cloud.githubusercontent.com/assets/13245874/9871373/36fae0f0-5bce-11e5-8f7d-2c7746536c70.png)

**Comment by gempesaw** [comment]
not OP, but, having similar issues 

info: 
OS X 10.10.5
jdk 1.7
installed eclipse 4.5 mars
trying to use eclim-2.5.0.jar to install

The error message for not choosing the correct `eclipse.home` is partially covered.
![Alt text](https://monosnap.com/file/9Iyffk4ZtiAzTVkp4ehkyIEm5mQBFS.png)

and, like @mn-green , I can't figure out which eclipse directory to use to appease the eclim installer. It's particularly confusing since the mars Eclipse installer has a handful of different versions of Eclipse to install, and I'm not sure which Eclipse version to pick, either.

thanks for eclim btw! pretty excited to get it set up and running with emacs :)

**Comment by si-mikey** [comment]
Bump gempesaw's comment. I am having the same problem. I can't see the error messages to know what to do. 
<img width="612" alt="screen shot 2015-09-17 at 4 01 52 pm" src="https://cloud.githubusercontent.com/assets/1561914/9944716/22777af0-5d57-11e5-924f-b4ae551b3b72.png">

**Comment by malensek** [comment]
I am having the same problem with the installer version of Eclipse Mars -- the jars that the installer looks for are nowhere to be found in the installed version (I selected "Eclipse IDE for Java Developers")

However, everything works as usual if I download the *non-installer* version of Eclipse. It's still a Mac OS .app bundle, but you can point the installer at /Path/To/Eclipse.app/Contents/Eclipse and everything works.

**Comment by gempesaw** [comment]
> However, everything works as usual if I download the non-installer version of Eclipse. It's still a Mac OS .app bundle, but you can point the installer at /Path/To/Eclipse.app/Contents/Eclipse and everything works.

Oh, thanks for the hint! I couldn't figure that out. Pulling [this Eclipse.app](http://take.ms/3nepB) into my `/Applications` and using that in the eclim installer worked for me too. Hurrah!

**Comment by ilanpillemer** [comment]
seems installer puts the plugins under  `.p2/pool` directory in the home directory.

**Comment by voltecrus** [comment]
thanks @ilanpillemer! pointing the installer to ~/.p2/pool made the installer work.

**Comment by jabocg** [comment]
Still getting the unreadable text bug, and forced to use non-installer version of Eclipse.

**Comment by ervandew** [comment]
I'm closing this out since the eclim gui installer has been replaced with a command line installer.
