### ISSUE TITLE
invalid eclipse home when eclipse is installed using the new eclipse installer

### ISSUE THREAD

**Issue by shenhai-ran** [ervandew/eclim#436]
I use Eclipse installer to install Eclipse jave IDE on Mac OS. By default it is put at ~/eclipse/java-mars/...
Then I start to install eclim with the GUI, however at the step to chose Eclipse home, now matter which folder I specify, it gives error
Invalid eclipse home (no 'plugins/org.eclipse.equinox.launcher_*.jar' found)

And in the eclipse.app folder I can not find any thing related to plugins/....jar.

**Comment by ervandew** [comment]
This is a known issue that I haven't had time to get to (the eclipse installer didn't even work on my linux machine). For now you can use the archive eclipse installs instead (*.tar.gz).

Unfortunately I don't see a .zip download of eclipse for windows users anymore. They might have one buried on the eclipse site somewhere, so if someone comes across it, please post it here.

**Comment by ecoal95** [comment]
I had the same problem and gave up (installed the .tar.gz)

Just in case it helps, the `eclipse/p2` folder in the `tar.gz`, was `$HOME/.p2` after running the installer.

**Comment by Haktrum** [comment]
On the Eclipse installer: open the menu (bars button), switch to advanced mode, disable Bundle Pool and install Eclipse. Now it should work.

**Comment by melaus** [comment]
I pointed my "Eclipse Home" to /Application/eclipse/java_mars/Eclipse.app/Contents/Eclipse and it works. I think it is because the app is now a modern encapsulated OS X application.

**Comment by The33Coder** [comment]
I have same problem and it's fine for me, withe @Haktrum  solution and @melaus.

**Comment by capitanbatata** [comment]
I'm running Ubuntu 15.04, and I've installed Eclipse Mars using the eclipse installer.

The Eclim installer complains about the Eclipse home not being a valid one (it shows the following contents):

    ls ~/opt/eclipse/java-mars/eclipse/
    configuration  dropins  eclipse  eclipse.ini  icon.xpm  readme

So no plugins folder, which is what the installer expects in the eclipse-home folder.

I've tried what @Haktrum suggested, without any luck. Is there any other workaround?

**Comment by ervandew** [comment]
@capitanbatata 
The easiest workaround is to not use the eclipse installer. Use one of the tar.gz files from them instead.

**Comment by capitanbatata** [comment]
@ervandew Thanks. That did the trick.

**Comment by alexmsmartins** [comment]
Hi @capitanbatata 

Try using `~/.p2/pool` as you eclipse home. This should solve your problem and, at least, get you in the next screen.

**Comment by edouardberthe** [comment]
Big 👍 to @Haktrum + @melaus

**Comment by kalhauge** [comment]
So I followed @Haktrum's fix, but with little luck:

```
java -Dvim.skip=true -Declipse.home=$HOME/java-neon/Eclipse.app/Contents/Eclipse -jar Downloads/eclim_2.6.0.jar install
```

The I run into the problem, "java.lang.RuntimeException: error:  out: An error has occurred. See the log file", with the first error in the being:

```
!ENTRY org.eclipse.wst.dtd.core 4 0 2016-07-29 06:47:39.771
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.wst.dtd.core [434]
```

and 

```
!ENTRY org.eclipse.osgi 4 0 2016-07-29 06:47:42.930
!MESSAGE Application error
!STACK 1
java.lang.RuntimeException: Application "org.eclim.installer.application" could not be found in the registry. The applications available are: org.eclipse.ant.core.antRunner, org.eclipse.equinox.app.error, org.eclipse.equinox.p2.director, org.eclipse.equinox.p2.garbagecollector.application, org.eclipse.equinox.p2.publisher.InstallPublisher, org.eclipse.equinox.p2.publisher.EclipseGenerator, org.eclipse.equinox.p2.publisher.ProductPublisher, org.eclipse.equinox.p2.publisher.FeaturesAndBundlesPublisher, org.eclipse.equinox.p2.reconciler.application, org.eclipse.equinox.p2.repository.repo2runnable, org.eclipse.equinox.p2.repository.metadataverifier, org.eclipse.equinox.p2.artifact.repository.mirrorApplication, org.eclipse.equinox.p2.metadata.repository.mirrorApplication, org.eclipse.equinox.p2.touchpoint.natives.nativePackageExtractor, org.eclipse.equinox.p2.updatesite.UpdateSitePublisher, org.eclipse.equinox.p2.publisher.UpdateSitePublisher, org.eclipse.equinox.p2.publisher.CategoryPublisher.
```

Up to this point I was using Eclipse-Neon, when changing to Eclipse-Mars everything worked perfectly.

**Comment by layer3switch** [comment]
I'm not sure if this is still ongoing issue, but this is how I resolved the problem with MacOSX application "Eclipse-Neon" by using unattended installation mode using ```Homebrew```. I found that during interactive installation using "Eclipse-install.app", ```$HOME/.p2/pool``` contains configuration, features, and plugins directory while ```$HOME/Applications/Eclipse.app/Content/Eclipse``` directory contains features and plugins. To make things worst, configuration/config.ini contains horribly formatted paths such as ```../../../../.p2/```.

Homebrew cask for eclipse-jee installs all into ```/Applications/Eclipse.app``` path and ```$HOME/.p2``` only contains pools.info file and empty profiles.info file. Once Homebrew eclipse-jee installation completed, ```java -Dvim.files=$HOME/.vim -Declipse.home=/Applications/Eclipse.app/Contents/Eclipse -jar eclim_2.6.0.jar install``` completes successfully.

**Comment by Hastradamus** [comment]
I was having the same issue with OSX 10.11.6, eclim_2.6.0.jar, and Eclipse 4.6.0 (I believe). The issue I was having, was I was getting an error from the installer not accepting the path to eclipse, and I was unable to see what error it was giving me. I didn't realize that I need to go to the Applications folder in my root directory, and point it to Eclipse.app/Contents/Eclipse from there. So the path that it accepted end the end was /Applications/Eclipse.app/Contents/Eclipse. This gets me past the page, but I encountered another error later on. I'm going to download Eclipse mars and try again.

**Comment by Hastradamus** [comment]
With my above stated setup, OS, eclim 2.5.0, and eclipse 4.5 mars, installation went off without a hitch

**Comment by JESii** [comment]
FYI installation notes:
`eclim 2.6.0`
`Eclipse 4.6.3RC3`

Home directory was: `/Applications/Eclipse.app/Contents/Eclipse` as noted above

Had to skip installing the 'Web Developer' plugin as a later version was already installed in Eclipse than the one that eclim was trying to install... something like 8.2.1 versus 8.2.2? (copy from the error box didn't work)

**Comment by arcseldon** [comment]
Found the solution offered by layer3switch [here](https://github.com/ervandew/eclim/issues/436#issuecomment-247580435) worked - for the reasons he gave. Using the eclim installer was splitting features folders etc inside `.p2` which threw the eclim installer. Using the cask, everything was under one directory.

**Comment by ervandew** [comment]
I'm closing this out since I just released a new installer for eclim that should solve all the issues related to attempting to use the old gui eclim installer against eclipse installed via their gui installer.
