### ISSUE TITLE
workench.xmi in $HOME/

### ISSUE THREAD

**Issue by TiBeN** [ervandew/eclim#445]
Hi, 
I use eclim 2.5.0 with ubuntu Wily.
There is a file "workbench.xmi" in my $HOME directory. If i erase it, it is recreated.
It is not a big issue but is it possible to tell Eclim/Eclipse to store it elsewhere like $HOME/.ecli{pse,m}/ ?
 
Thanks

**Comment by ervandew** [comment]
That file is created by eclipse and I think it's created in whatever your current working directory is when eclipse (eclimd) starts. Last I looked, I couldn't find a way to tell eclipse to put that file somewhere else.

**Comment by TiBeN** [comment]
Yes, you are right it is created on the current directory.
Because i launch eclimd as a systemd service, i added 
```
WorkingDirectory=/home/tiben/var/eclipse
```
which solved my issue.
Thank you and many thanks for Eclim, i have used it every days for more than one year.
