### ISSUE TITLE
Don't generate comments with :JavaGet[Set]

### ISSUE THREAD

**Issue by TiBeN** [ervandew/eclim#450]
Hi, 
Is it possible to generate getters setters without comments?
Theses comments are more like noise than useful information...

**Comment by ervandew** [comment]
I think you can open up the eclipse gui and configure eclipse to omit those:

    Preferences > Java > Code Style > Code Templates

then under the "Comments" section you can probably just remove the comment template for "Getters" and "Setters".

**Comment by TiBeN** [comment]
it works thanks!
