### ISSUE TITLE
Installation error on Windows 8.1

### ISSUE THREAD

**Issue by unix-junkie** [ervandew/eclim#455]
I'm trying to install Eclim 2.5.0 on Eclipse 4.5.2 (Mars.2, CDT+JDT+WST) on Windows 8.1.

The error message I receive is: "eclipse\plugins\org.eclim_2.5.0\bin does not exist."

Full log is attached
[eclim-installer.txt](https://github.com/ervandew/eclim/files/154705/eclim-installer.txt)

**Comment by mamboking** [comment]
I'm seeing the same thing on Windows 7 with eclim_2.6.0 and Neon.

**Comment by ervandew** [comment]
I'm closing this out since going forward eclim is only supporting linux and osx.
