### ISSUE TITLE
Can I get eclim to return the start column of its completions?

### ISSUE THREAD

**Issue by vincentwoo** [ervandew/eclim#457]
Hi there! I'm writing a new editor integration for eclim that operates over the command line. I'm having some trouble issuing Java completions. For example, with a command like: 

`eclipse/eclim -command java_complete -p eclipse_project -f src/Solution.java -o #{offset} -e utf-8 -l standard`

I get results like

```json
{
  "completions": [
    {
      "completion": "Bits;",
      "menu": "Bits - java.io",
      "info": "Bits - java.io",
      "type": "t"
    },
    {
      "completion": "BlockDataInputStream;",
      "menu": "BlockDataInputStream - java.io",
      "info": "BlockDataInputStream - java.io",
      "type": "t"
    }
  ]
}
```

However, it doesn't seem to return the character offset or column number the completion began on.

So, if I issue an autocompletion request for:

`object.met` (completing to `object.method`)

vs

`object.`

It's difficult to know, in the editor, where the completion results should be inserted. Is there a way for eclim to return it's opinion on where the autocomplete token should go?

**Comment by vincentwoo** [comment]
In fact there is a very helpful existing method in `jdt` that gives us exactly what we want: [CompletionProposal#getReplaceStart()](http://help.eclipse.org/juno/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Forg%2Feclipse%2Fjdt%2Fcore%2FCompletionProposal.html&anchor=getReplaceStart()).

I'm trying to figure out how to plumb it through Eclim but am struggling - I can't figure out where the serialization format for 

```json
{"completions":[{
    "completion":"args",
    "menu":"args : String[]",
    "info":"args : String[]",
    "type":"v"
  },{
    "completion":"greet()",
    "menu":"greet() : void - Hello",
    "info":"greet() : void - Hello",
    "type":"f"
  },{
    "completion":"Hello",
    "menu":"Hello - test",
    "info":"Hello - test",
    "type":"t"
  },{
    "completion":"main(",
    "menu":"main(String... args) : void - Hello",
    "info":"main(String... args) : void - Hello",
    "type":"f"}
  ]}
```

is set

**Comment by ervandew** [comment]
The serialization is all handled by `gson` in `org.eclim.command.Main`. Basically `gson` can create json objects based on private properties of an object. So in this case a new property would need to be added to the `org.eclim.core.command.CodeCompleteResult` object, and then any command dependent on that object should be updated accordingly.

**Comment by vincentwoo** [comment]
@ervandew Cool, think I figured most of it out! I wrote a fairly simple PR, mind taking a look? In my local testing it appears to work flawlessly (and resolves the related issue too).

**Comment by ervandew** [comment]
Looks good to me.
