### ISSUE TITLE
installer did not work with eclipse 4.6.0.rc1 neon

### ISSUE THREAD

**Issue by mschaaf** [ervandew/eclim#472]
It reports a missing/unsupported eclipse verison.
Copying the feature and plugin parts by hand let the plugin work in eclipse neon.

**Comment by emmanueltouzery** [comment]
I'm hitting the same issue, the installer refuses to even try. I am sorry, could you explain where to copy the files to make it work?

**Comment by emmanueltouzery** [comment]
Ok I made the installer work by editing the jar file... I tried looking at the source but it needs ant to build and so on... So to fix the installer manually... Extract the jar file (which is zip), and edit resources/install.properties. Modify 

    -  eclipse.version.minor=5
    +  eclipse.version.minor=6

Obviously it's a huge hack and so on...

**Comment by BimbaLaszlo** [comment]
I think this can be closed.
