### ISSUE TITLE
Failed to determine your eclipse version message when running installer

### ISSUE THREAD

**Issue by chuymax** [ervandew/eclim#476]
Environment:
Windows 7 (64 bit).
Vim 7.4 patch 1-2066 (32 bits).
Eclipse 4.6.0 (build id 20160613-1800) (32 bits).

Steps:
1. Run installer.
2. Press Next at welcome screen.
3. Accept license and press Next.
4. Select vim files folder (C:/Users/Max/.vim) and press Next.
5. Select eclipse folder (C:/eclipse/java-neon/eclipse) and press Next.
6. Receive message errors:
"One or more requirements could not be determined. Please click them for"
[click first row]
"Failed to determine your eclipse version (check /tmp/install.log for details).
7. No logs are available under C:\tmp\install.log.

NOTE: I repeated the same steps with Vim 32 bits and Eclipse 4.6 (64 bits) and I get the same error.

![capture0](https://cloud.githubusercontent.com/assets/1208947/17337091/49341a28-58af-11e6-8556-b64d45dca49a.JPG)
![capture1](https://cloud.githubusercontent.com/assets/1208947/17337090/49329482-58af-11e6-8bb7-d8aa67a79478.JPG)

**Comment by chuymax** [comment]
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) Client VM (build 25.91-b14, mixed mode, sharing)

**Comment by ervandew** [comment]
Did you install eclipse using their gui installer? The eclim installer does not currently support the file layout the gui installer uses by default.

**Comment by chuymax** [comment]
Thanks. I used eclipse zip file installation method and now eclim installer works.
