### ISSUE TITLE
Can't install on OSX

### ISSUE THREAD

**Issue by mrdanimal** [ervandew/eclim#479]
I'm on Java 1.8, using the graphical installer.

There are a few issues, one of which I was able to workaround, but one I'm not:

* I get an error that `/Applications/Eclipse/java-neon/Eclipse.app/Contents/Eclipse/features` doesn't exist. The installer doesn't provide any options except to exit and restart the installation. I exit the installer, manually create the dir, and it proceeds past that point
* Then I get an error that the file `/Applications/Eclipse/java-neon/Eclipse.app/Contents/Eclipse/plugins/org.eclim_2.6.0/bin/eclimd` doesn't exist. Since that's what I'm trying to install, I can't think of a workaround

Any help would be greatly appreciated. Let me know if you need any other info. Thanks!

**Comment by ervandew** [comment]
The eclim installer does not support the file layout created by the eclipse installer. If you install eclipse using one of the *.tar.gz files, then the eclim installer should work fine.

http://www.eclipse.org/downloads/eclipse-packages/?osType=macosx&release=undefined

**Comment by mrdanimal** [comment]
Ah, thanks for the quick response!

**Comment by dozzman** [comment]
Just as an FYI, I managed to get it working using the following headless installation:

```
java \
-Dvim.files=$HOME/.vim \
-Declipse.home=$HOME/eclipse/java-neon/Eclipse.app/Contents/Eclipse \
-Declipse.local=$HOME/.p2/pool \
-jar ~/Downloads/eclim_2.6.0.jar \
install
```

on a fresh installation of eclipse. I mentioned this in #482 but thought it was more appropriate here. I wen't through pretty much the same steps as #484 before I got to this solution.

**Comment by ngfgrant** [comment]
java \
  -Dvim.files=$HOME/.vim \
  -Declipse.home=/Applications/Eclipse.app/Contents/Eclipse/
  -jar eclim_2.7.0.jar install
