### ISSUE TITLE
Some of installer UI hidden on Mac OS X El Capitan

### ISSUE THREAD

**Issue by boompig** [ervandew/eclim#480]
See screenshot:

![screen shot 2016-08-25 at 4 48 58 pm](https://cloud.githubusercontent.com/assets/2791268/17989659/f648671e-6ae3-11e6-8c40-ac895a735f24.png)

Also on the next screen:

![screen shot 2016-08-25 at 4 50 53 pm](https://cloud.githubusercontent.com/assets/2791268/17989688/1c532ae8-6ae4-11e6-871c-dd4366c0c740.png)

And 2 screens after that:

![screen shot 2016-08-25 at 4 51 44 pm](https://cloud.githubusercontent.com/assets/2791268/17989708/3acd0d2c-6ae4-11e6-9c7d-9e8721ec9aa2.png)

Mac OS X version: 10.11.6 (El Capitan)
eclim version: 2.6.0

**Comment by ervandew** [comment]
I'm closing this out since the gui installer has been replaced with a command line installer.
