### ISSUE TITLE
eclim fails to detect Eclipse version on Mac OS X El Capitan

### ISSUE THREAD

**Issue by boompig** [ervandew/eclim#482]
Mac OS X version: 10.11.6 (El Capitan)
Eclipse Version: 4.6.0 (Neon)
eclim version: 2.6.0

Set the Eclipse root directory as: `~/eclipse/java-neon/Eclipse.app/Contents/Eclipse` (to get around #436)

See screenshot: 
![screen shot 2016-08-25 at 4 51 44 pm](https://cloud.githubusercontent.com/assets/2791268/17989792/da76bc24-6ae4-11e6-8c03-241a1a82d78c.png)

**Comment by dozzman** [comment]
I had the same problem and many more along the way. I managed to get it working by running the installation headless with:

```
java \
-Dvim.files=$HOME/.vim \
-Declipse.home=$HOME/eclipse/jee-latest-released/Eclipse.app/Contents/Eclipse \
-Declipse.local=$HOME/.p2/pool \
-jar ~/Downloads/eclim_2.6.0.jar \
install
```

on a fresh installation of eclipse. If you have tried a few times you may need to run `clean` or `uninstall` as well, although I haven't tested those.

**Comment by kit90** [comment]
This bug is present when Eclipse is installed through Oomph Installer. The bug occurs because the `features` directory is not being detected, which in this case is present in `~/.p2/pool`. The above fix by @dozzman works well in Ubuntu too.

**Comment by HarrisonB** [comment]
Using @dozzman's solution resulted in a successful build, but `eclimd` points `plugins/org.eclim_2.6.0/bin/eclimd` which doesn't exist, as the plugin was installed under the `.p2/pool/plugins/` directory. Same for `eclim`. The actual executable is in `.p2/pool/plugins/org.eclim_2.6.0/bin`.

**Comment by kit90** [comment]
Until this issue is fixed, a temporary solution can be (after `cd`'ing to `eclipse` directory):
`ln -s -f ~/.p2/pool/plugins/org.eclim_2.6.0/bin/eclim ./eclim`
`ln -s -f ~/.p2/pool/plugins/org.eclim_2.6.0/bin/eclimd ./eclimd`

**Comment by HarrisonB** [comment]
Did the same thing...working for me so far.

**Comment by ervandew** [comment]
I'm closing this out since I just released a new installer for eclim that should solve all the issues related to attempting to use the old gui eclim installer against eclipse installed via their gui installer.
