### ISSUE TITLE
Cannot copy-paste error text on Mac OS X El Capitan

### ISSUE THREAD

**Issue by boompig** [ervandew/eclim#483]
Screen on which error occurs:

![screen shot 2016-08-25 at 5 02 16 pm](https://cloud.githubusercontent.com/assets/2791268/17989925/e652249c-6ae5-11e6-9af5-bc4acbb48647.png)

I tried to copy the text, but it seems copy is disabled? I see no reason for this behaviour.

Mac OS X version: 10.11.6 (El Capitan)
eclim version: 2.6.0

**Comment by ervandew** [comment]
I'm closing this out since the newly released command line installer for eclim should solve this.
