### ISSUE TITLE
Failed to install eclim on Mac OS X El Capitan

### ISSUE THREAD

**Issue by boompig** [ervandew/eclim#484]
Error seen here:
![screen shot 2016-08-25 at 5 02 16 pm](https://cloud.githubusercontent.com/assets/2791268/17989936/0cd06a2a-6ae6-11e6-9d84-e5100f50c01f.png)

I would copy the text, but I can't due to #483. Also even after dialog box resized, more of the error text is not shown (ellipsis is not expanded).

Mac OS X version: 10.11.6 (El Capitan)
Eclipse Version: 4.6.0 (Neon)
eclim version: 2.6.0

Screenshot of summary screen before clicking next:
![screen shot 2016-08-25 at 5 01 51 pm](https://cloud.githubusercontent.com/assets/2791268/17989947/24b8d348-6ae6-11e6-82cb-b8b161fe159a.png)

**Comment by boompig** [comment]
I manually created `features` directory in `~/eclipse/java-neon/Eclipse.app/Contents/Eclipse` and got the following error (screenshot):

![screen shot 2016-08-25 at 5 10 06 pm](https://cloud.githubusercontent.com/assets/2791268/17990020/d1277bc0-6ae6-11e6-93ee-f71d30f02c5c.png)

**Comment by ervandew** [comment]
See #479
