### ISSUE TITLE
Cannot build against fresh Neon install, Debian 64bits for Java development

### ISSUE THREAD

**Issue by iago-lito** [ervandew/eclim#485]
Hey, this is Debian stretch 64bit speaking, with Eclipse freshly installed in `/opt/Oracle/java-neon/eclipse` (owned by user): here is the output of the [build install](http://eclim.org/install.html#install-source) :

    $ git clone git://github.com/ervandew/eclim.git 
    $ cd eclim
    $ ant -Declipse.home=/opt/Oracle/java-neon/eclipse
    Buildfile: /home/iago-lito/Téléchargements/eclim/build.xml

    deploy:

    gant:
         [echo] ${eclipse}: /opt/Oracle/java-neon/eclipse
         [echo] # Skipping org.eclim.pdt, missing org.eclipse.php
         [echo] # Skipping org.eclim.wst, missing org.eclipse.wst.web_ui.feature
         [echo] # Skipping org.eclim.adt, missing com.android.ide.eclipse.adt.feature
         [echo] # Skipping org.eclim.sdt, missing org.scala-ide.sdt.feature
         [echo] # Skipping org.eclim.dltk, missing org.eclipse.dltk.core
         [echo] # Skipping org.eclim.cdt, missing org.eclipse.cdt
         [echo] # Skipping org.eclim.jdt, missing org.eclipse.jdt
         [echo] # Skipping org.eclim.groovy, missing org.codehaus.groovy.jdt.patch
         [echo] # Skipping org.eclim.dltkruby, missing org.eclipse.dltk.ruby
         [echo] # Skipping org.eclim.pydev, missing org.python.pydev.feature
         [echo] Plugins:
    deploy:
    deploy.eclipse:
    build:
    build.eclipse:
    init:
         [echo] eclim.version: 2.6.0.2-g5d48cfa
         [echo] eclim.release: 2.6.0
         [echo] eclim.release.indigo: none
    ------ init
         [echo] 
         [echo] building plugin: org.eclim
        [mkdir] Created dir: /home/iago-lito/Téléchargements/eclim/build/temp/eclipse/plugins/org.eclim_2.6.0.2-g5d48cfa
        [mkdir] Created dir: /home/iago-lito/Téléchargements/eclim/build/temp/classes/org.eclim
        [javac] Compiling 40 source files to /home/iago-lito/Téléchargements/eclim/build/temp/classes/org.eclim
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/plugin/AbstractPluginResources.java:42: error: package org.eclipse.core.runtime does not exist
        [javac] import org.eclipse.core.runtime.FileLocator;
        [javac]                                ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/logging/Logger.java:19: error: package org.eclipse.core.resources does not exist
        [javac] import org.eclipse.core.resources.ResourcesPlugin;
        [javac]                                  ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/command/Main.java:40: error: package org.eclipse.swt.widgets does not exist
        [javac] import org.eclipse.swt.widgets.Display;
        [javac]                               ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/command/ReloadCommand.java:25: error: package org.eclipse.core.runtime does not exist
        [javac] import org.eclipse.core.runtime.Platform;
        [javac]                                ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/command/ReloadCommand.java:27: error: package org.osgi.framework does not exist
        [javac] import org.osgi.framework.Bundle;
        [javac]                          ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/command/ReloadCommand.java:28: error: package org.osgi.framework does not exist
        [javac] import org.osgi.framework.FrameworkListener;
        [javac]                          ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/command/ReloadCommand.java:30: error: package org.osgi.framework.wiring does not exist
        [javac] import org.osgi.framework.wiring.FrameworkWiring;
        [javac]                                 ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/EclimApplication.java:32: error: package org.eclipse.e4.ui.internal.workbench does not exist
        [javac] import org.eclipse.e4.ui.internal.workbench.E4Workbench;
        [javac]                                            ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/EclimApplication.java:34: error: package org.eclipse.equinox.app does not exist
        [javac] import org.eclipse.equinox.app.IApplicationContext;
        [javac]                               ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/EclimApplication.java:36: error: package org.eclipse.jface.preference does not exist
        [javac] import org.eclipse.jface.preference.IPreferenceStore;
        [javac]                                    ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/EclimApplication.java:38: error: package org.eclipse.ui does not exist
        [javac] import org.eclipse.ui.IWorkbench;
        [javac]                      ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/EclimApplication.java:39: error: package org.eclipse.ui does not exist
        [javac] import org.eclipse.ui.PlatformUI;
        [javac]                      ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/EclimApplication.java:41: error: package org.eclipse.ui.internal does not exist
        [javac] import org.eclipse.ui.internal.IPreferenceConstants;
        [javac]                               ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/EclimApplication.java:43: error: package org.eclipse.ui.internal.ide.application does not exist
        [javac] import org.eclipse.ui.internal.ide.application.IDEApplication;
        [javac]                                               ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/EclimApplication.java:45: error: package org.eclipse.ui.internal.util does not exist
        [javac] import org.eclipse.ui.internal.util.PrefUtil;
        [javac]                                    ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/EclimApplication.java:54: error: cannot find symbol
        [javac]   extends IDEApplication
        [javac]           ^
        [javac]   symbol: class IDEApplication
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/EclimApplication.java:66: error: cannot find symbol
        [javac]   public Object start(IApplicationContext context)
        [javac]                       ^
        [javac]   symbol:   class IApplicationContext
        [javac]   location: class EclimApplication
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/EclimDaemon.java:46: error: package org.eclipse.core.resources does not exist
        [javac] import org.eclipse.core.resources.ResourcesPlugin;
        [javac]                                  ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/EclimDaemon.java:48: error: package org.eclipse.core.runtime does not exist
        [javac] import org.eclipse.core.runtime.FileLocator;
        [javac]                                ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/EclimDaemon.java:49: error: package org.eclipse.core.runtime does not exist
        [javac] import org.eclipse.core.runtime.IPath;
        [javac]                                ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/EclimDaemon.java:50: error: package org.eclipse.core.runtime does not exist
        [javac] import org.eclipse.core.runtime.Path;
        [javac]                                ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/EclimDaemon.java:51: error: package org.eclipse.core.runtime does not exist
        [javac] import org.eclipse.core.runtime.Platform;
        [javac]                                ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/EclimDaemon.java:53: error: package org.eclipse.core.runtime.jobs does not exist
        [javac] import org.eclipse.core.runtime.jobs.IJobManager;
        [javac]                                     ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/EclimDaemon.java:54: error: package org.eclipse.core.runtime.jobs does not exist
        [javac] import org.eclipse.core.runtime.jobs.Job;
        [javac]                                     ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/EclimDaemon.java:56: error: package org.osgi.framework does not exist
        [javac] import org.osgi.framework.Bundle;
        [javac]                          ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/EclimDaemon.java:57: error: package org.osgi.framework does not exist
        [javac] import org.osgi.framework.FrameworkEvent;
        [javac]                          ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/EclimDaemon.java:58: error: package org.osgi.framework does not exist
        [javac] import org.osgi.framework.FrameworkListener;
        [javac]                          ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/EclimDaemon.java:71: error: cannot find symbol
        [javac]   implements FrameworkListener
        [javac]              ^
        [javac]   symbol: class FrameworkListener
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/EclimDaemon.java:406: error: cannot find symbol
        [javac]   public synchronized void frameworkEvent(FrameworkEvent event)
        [javac]                                           ^
        [javac]   symbol:   class FrameworkEvent
        [javac]   location: class EclimDaemon
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/EclimDaemon.java:419: error: cannot find symbol
        [javac]   private boolean jobsRunning(IJobManager manager)
        [javac]                               ^
        [javac]   symbol:   class IJobManager
        [javac]   location: class EclimDaemon
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/EclimPlugin.java:21: error: package org.eclipse.core.runtime does not exist
        [javac] import org.eclipse.core.runtime.FileLocator;
        [javac]                                ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/EclimPlugin.java:22: error: package org.eclipse.core.runtime does not exist
        [javac] import org.eclipse.core.runtime.Plugin;
        [javac]                                ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/EclimPlugin.java:24: error: package org.eclipse.swt.widgets does not exist
        [javac] import org.eclipse.swt.widgets.Display;
        [javac]                               ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/EclimPlugin.java:25: error: package org.eclipse.swt.widgets does not exist
        [javac] import org.eclipse.swt.widgets.Shell;
        [javac]                               ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/EclimPlugin.java:27: error: package org.osgi.framework does not exist
        [javac] import org.osgi.framework.BundleContext;
        [javac]                          ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/EclimPlugin.java:35: error: cannot find symbol
        [javac]   extends Plugin
        [javac]           ^
        [javac]   symbol: class Plugin
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/EclimPlugin.java:56: error: cannot find symbol
        [javac]   public void start(BundleContext context)
        [javac]                     ^
        [javac]   symbol:   class BundleContext
        [javac]   location: class EclimPlugin
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/EclimPlugin.java:74: error: cannot find symbol
        [javac]   public void stop(BundleContext context)
        [javac]                    ^
        [javac]   symbol:   class BundleContext
        [javac]   location: class EclimPlugin
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/EclimPlugin.java:94: error: cannot find symbol
        [javac]   public static Shell getShell()
        [javac]                 ^
        [javac]   symbol:   class Shell
        [javac]   location: class EclimPlugin
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/EclimStartup.java:21: error: package org.eclipse.ui does not exist
        [javac] import org.eclipse.ui.IStartup;
        [javac]                      ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/EclimStartup.java:22: error: package org.eclipse.ui does not exist
        [javac] import org.eclipse.ui.IWorkbench;
        [javac]                      ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/EclimStartup.java:23: error: package org.eclipse.ui does not exist
        [javac] import org.eclipse.ui.PlatformUI;
        [javac]                      ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/EclimStartup.java:32: error: cannot find symbol
        [javac]   implements IStartup
        [javac]              ^
        [javac]   symbol: class IStartup
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/e4/HeadlessPresentationEngine.java:21: error: package javax.inject does not exist
        [javac] import javax.inject.Inject;
        [javac]                    ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/e4/HeadlessPresentationEngine.java:22: error: package javax.inject does not exist
        [javac] import javax.inject.Named;
        [javac]                    ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/e4/HeadlessPresentationEngine.java:24: error: package org.eclipse.e4.core.di.annotations does not exist
        [javac] import org.eclipse.e4.core.di.annotations.Optional;
        [javac]                                          ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/e4/HeadlessPresentationEngine.java:26: error: package org.eclipse.e4.ui.internal.workbench does not exist
        [javac] import org.eclipse.e4.ui.internal.workbench.E4Workbench;
        [javac]                                            ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/e4/HeadlessPresentationEngine.java:28: error: package org.eclipse.e4.ui.internal.workbench.swt does not exist
        [javac] import org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine;
        [javac]                                                ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/e4/HeadlessPresentationEngine.java:30: error: package org.eclipse.e4.ui.model.application.ui does not exist
        [javac] import org.eclipse.e4.ui.model.application.ui.MUIElement;
        [javac]                                              ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/e4/HeadlessPresentationEngine.java:32: error: package org.eclipse.e4.ui.model.application.ui.basic does not exist
        [javac] import org.eclipse.e4.ui.model.application.ui.basic.MWindow;
        [javac]                                                    ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/e4/HeadlessPresentationEngine.java:40: error: cannot find symbol
        [javac]   extends PartRenderingEngine
        [javac]           ^
        [javac]   symbol: class PartRenderingEngine
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/e4/HeadlessPresentationEngine.java:50: error: cannot find symbol
        [javac]   protected Object createWidget(MUIElement element, Object parent)
        [javac]                                 ^
        [javac]   symbol:   class MUIElement
        [javac]   location: class HeadlessPresentationEngine
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/e4/HeadlessPresentationEngine.java:59: error: cannot find symbol
        [javac]   protected boolean someAreVisible(List<MWindow> windows)
        [javac]                                         ^
        [javac]   symbol:   class MWindow
        [javac]   location: class HeadlessPresentationEngine
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummySelectionProvider.java:19: error: package org.eclipse.jface.viewers does not exist
        [javac] import org.eclipse.jface.viewers.ISelection;
        [javac]                                 ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummySelectionProvider.java:20: error: package org.eclipse.jface.viewers does not exist
        [javac] import org.eclipse.jface.viewers.ISelectionChangedListener;
        [javac]                                 ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummySelectionProvider.java:21: error: package org.eclipse.jface.viewers does not exist
        [javac] import org.eclipse.jface.viewers.ISelectionProvider;
        [javac]                                 ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummySelectionProvider.java:30: error: cannot find symbol
        [javac]   implements ISelectionProvider
        [javac]              ^
        [javac]   symbol: class ISelectionProvider
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummySelectionProvider.java:32: error: cannot find symbol
        [javac]   private ISelection selection;
        [javac]           ^
        [javac]   symbol:   class ISelection
        [javac]   location: class DummySelectionProvider
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummySelectionProvider.java:34: error: cannot find symbol
        [javac]   public DummySelectionProvider (ISelection selection)
        [javac]                                  ^
        [javac]   symbol:   class ISelection
        [javac]   location: class DummySelectionProvider
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummySelectionProvider.java:39: error: cannot find symbol
        [javac]   public void addSelectionChangedListener(ISelectionChangedListener listener)
        [javac]                                           ^
        [javac]   symbol:   class ISelectionChangedListener
        [javac]   location: class DummySelectionProvider
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummySelectionProvider.java:43: error: cannot find symbol
        [javac]   public ISelection getSelection()
        [javac]          ^
        [javac]   symbol:   class ISelection
        [javac]   location: class DummySelectionProvider
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummySelectionProvider.java:48: error: cannot find symbol
        [javac]   public void removeSelectionChangedListener(ISelectionChangedListener listener)
        [javac]                                              ^
        [javac]   symbol:   class ISelectionChangedListener
        [javac]   location: class DummySelectionProvider
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummySelectionProvider.java:52: error: cannot find symbol
        [javac]   public void setSelection(ISelection selection)
        [javac]                            ^
        [javac]   symbol:   class ISelection
        [javac]   location: class DummySelectionProvider
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:21: error: package org.eclipse.jface.text does not exist
        [javac] import org.eclipse.jface.text.IDocument;
        [javac]                              ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:22: error: package org.eclipse.jface.text does not exist
        [javac] import org.eclipse.jface.text.IEventConsumer;
        [javac]                              ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:23: error: package org.eclipse.jface.text does not exist
        [javac] import org.eclipse.jface.text.IFindReplaceTarget;
        [javac]                              ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:24: error: package org.eclipse.jface.text does not exist
        [javac] import org.eclipse.jface.text.IRegion;
        [javac]                              ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:25: error: package org.eclipse.jface.text does not exist
        [javac] import org.eclipse.jface.text.ITextDoubleClickStrategy;
        [javac]                              ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:26: error: package org.eclipse.jface.text does not exist
        [javac] import org.eclipse.jface.text.ITextHover;
        [javac]                              ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:27: error: package org.eclipse.jface.text does not exist
        [javac] import org.eclipse.jface.text.ITextInputListener;
        [javac]                              ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:28: error: package org.eclipse.jface.text does not exist
        [javac] import org.eclipse.jface.text.ITextListener;
        [javac]                              ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:29: error: package org.eclipse.jface.text does not exist
        [javac] import org.eclipse.jface.text.ITextOperationTarget;
        [javac]                              ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:30: error: package org.eclipse.jface.text does not exist
        [javac] import org.eclipse.jface.text.IUndoManager;
        [javac]                              ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:31: error: package org.eclipse.jface.text does not exist
        [javac] import org.eclipse.jface.text.IViewportListener;
        [javac]                              ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:32: error: package org.eclipse.jface.text does not exist
        [javac] import org.eclipse.jface.text.TextPresentation;
        [javac]                              ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:33: error: package org.eclipse.jface.text does not exist
        [javac] import org.eclipse.jface.text.TextSelection;
        [javac]                              ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:35: error: package org.eclipse.jface.text.source does not exist
        [javac] import org.eclipse.jface.text.source.Annotation;
        [javac]                                     ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:36: error: package org.eclipse.jface.text.source does not exist
        [javac] import org.eclipse.jface.text.source.IAnnotationHover;
        [javac]                                     ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:37: error: package org.eclipse.jface.text.source does not exist
        [javac] import org.eclipse.jface.text.source.IAnnotationModel;
        [javac]                                     ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:38: error: package org.eclipse.jface.text.source does not exist
        [javac] import org.eclipse.jface.text.source.ISourceViewer;
        [javac]                                     ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:39: error: package org.eclipse.jface.text.source does not exist
        [javac] import org.eclipse.jface.text.source.SourceViewerConfiguration;
        [javac]                                     ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:41: error: package org.eclipse.jface.viewers does not exist
        [javac] import org.eclipse.jface.viewers.ISelectionProvider;
        [javac]                                 ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:43: error: package org.eclipse.swt.custom does not exist
        [javac] import org.eclipse.swt.custom.StyledText;
        [javac]                              ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:45: error: package org.eclipse.swt.graphics does not exist
        [javac] import org.eclipse.swt.graphics.Color;
        [javac]                                ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:46: error: package org.eclipse.swt.graphics does not exist
        [javac] import org.eclipse.swt.graphics.Point;
        [javac]                                ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:55: error: cannot find symbol
        [javac]   implements ISourceViewer
        [javac]              ^
        [javac]   symbol: class ISourceViewer
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:57: error: cannot find symbol
        [javac]   public IDocument document;
        [javac]          ^
        [javac]   symbol:   class IDocument
        [javac]   location: class DummyTextViewer
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:58: error: cannot find symbol
        [javac]   public ISelectionProvider selectionProvider;
        [javac]          ^
        [javac]   symbol:   class ISelectionProvider
        [javac]   location: class DummyTextViewer
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:59: error: cannot find symbol
        [javac]   private StyledText textWidget;
        [javac]           ^
        [javac]   symbol:   class StyledText
        [javac]   location: class DummyTextViewer
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:61: error: cannot find symbol
        [javac]   public DummyTextViewer (IDocument document, int offset, int length)
        [javac]                           ^
        [javac]   symbol:   class IDocument
        [javac]   location: class DummyTextViewer
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:70: error: cannot find symbol
        [javac]   public StyledText getTextWidget()
        [javac]          ^
        [javac]   symbol:   class StyledText
        [javac]   location: class DummyTextViewer
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:79: error: cannot find symbol
        [javac]   public void setUndoManager(IUndoManager undoManager)
        [javac]                              ^
        [javac]   symbol:   class IUndoManager
        [javac]   location: class DummyTextViewer
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:84: error: cannot find symbol
        [javac]       ITextDoubleClickStrategy strategy, String contentType)
        [javac]       ^
        [javac]   symbol:   class ITextDoubleClickStrategy
        [javac]   location: class DummyTextViewer
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:90: error: package org.eclipse.jface.text does not exist
        [javac]       org.eclipse.jface.text.IAutoIndentStrategy strategy, String contentType)
        [javac]                             ^
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:94: error: cannot find symbol
        [javac]   public void setTextHover(ITextHover textViewerHover, String contentType)
        [javac]                            ^
        [javac]   symbol:   class ITextHover
        [javac]   location: class DummyTextViewer
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:106: error: cannot find symbol
        [javac]   public void addViewportListener(IViewportListener listener)
        [javac]                                   ^
        [javac]   symbol:   class IViewportListener
        [javac]   location: class DummyTextViewer
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:110: error: cannot find symbol
        [javac]   public void removeViewportListener(IViewportListener listener)
        [javac]                                      ^
        [javac]   symbol:   class IViewportListener
        [javac]   location: class DummyTextViewer
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:114: error: cannot find symbol
        [javac]   public void addTextListener(ITextListener listener)
        [javac]                               ^
        [javac]   symbol:   class ITextListener
        [javac]   location: class DummyTextViewer
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:118: error: cannot find symbol
        [javac]   public void removeTextListener(ITextListener listener)
        [javac]                                  ^
        [javac]   symbol:   class ITextListener
        [javac]   location: class DummyTextViewer
        [javac] /home/iago-lito/Téléchargements/eclim/org.eclim/java/org/eclim/eclipse/jface/text/DummyTextViewer.java:122: error: cannot find symbol
        [javac]   public void addTextInputListener(ITextInputListener listener)
        [javac]                                    ^
        [javac]   symbol:   class ITextInputListener
        [javac]   location: class DummyTextViewer
        [javac] 100 errors

    BUILD FAILED
    /home/iago-lito/Téléchargements/eclim/build.xml:32: The following error occurred while executing this line:
    /home/iago-lito/Téléchargements/eclim/build.xml:165: : Compile failed; see the compiler error output for details.

    Total time: 2 seconds 

Here is the output of `ls /opt/Oracle/java-neon/eclipse -lah`:

    total 252K
    drwxr-xr-x  6 iago-lito iago-lito 4,0K sept. 10 18:21 .
    drwxr-xr-x  3 iago-lito iago-lito 4,0K sept. 10 18:11 ..
    drwxr-xr-x 11 iago-lito iago-lito 4,0K sept. 10 18:21 configuration
    drwxr-xr-x  2 iago-lito iago-lito 4,0K sept. 10 18:12 dropins
    -rwxr-xr-x  1 iago-lito iago-lito  79K juin   6 12:39 eclipse
    -rw-r--r--  1 iago-lito iago-lito  723 sept. 10 18:12 eclipse.ini
    -rw-r--r--  1 iago-lito iago-lito   60 mai    1 20:07 .eclipseproduct
    -rwxr-xr-x  1 iago-lito iago-lito 138K juin   6 12:39 icon.xpm
    drwxr-xr-x  2 iago-lito iago-lito 4,0K sept. 10 18:12 plugins
    drwxr-xr-x  2 iago-lito iago-lito 4,0K sept. 10 18:12 readme

Interestingly, the `plugins` folder only contains `org.eclipse.equinox.launcher_1.3.200.v20160318-1642.jar`.

The [gui installer](http://eclim.org/install.html#installer) also fails with :

    jar:file:/home/iago-lito/T%c3%a9l%c3%a9chargements/eclim_2.6.0.jar!/installer.xml:145: The following error occurred while executing this line:
    jar:file:/home/iago-lito/T%c3%a9l%c3%a9chargements/eclim_2.6.0.jar!/installer.xml:342: Directory does not exist: /opt/Oracle/java-neon/eclipse/features
        at org.apache.tools.ant.ProjectHelper.addLocationToBuildException(ProjectHelper.java:551)
        at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:460)
        at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:119)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:390)
        at org.apache.tools.ant.Target.performTasks(Target.java:411)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
        at org.formic.wizard.step.shared.InstallAction.execute(InstallAction.java:124)
        at org.formic.wizard.step.gui.InstallStep$1.run(InstallStep.java:162)
        at foxtrot.AbstractWorkerThread$1.run(AbstractWorkerThread.java:40)
        at java.security.AccessController.doPrivileged(Native Method)
        at foxtrot.AbstractWorkerThread.runTask(AbstractWorkerThread.java:36)
        at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:199)
        at foxtrot.workers.SingleWorkerThread.run(SingleWorkerThread.java:182)
        at java.lang.Thread.run(Thread.java:745)

Any idea what may be going wrong?

**Comment by ervandew** [comment]
Looks like you installed eclipse using their installer. If you instead use one of their tar.gz files you should be able to build/install just fine.

**Comment by iago-lito** [comment]
Indeed! Great :)
So **do not use Eclipse installer**, right? Maybe it is worth a line on [this section](http://eclim.org/install.html#requirements) ;)
Cheers!
