### ISSUE TITLE
Error detected while processing $Vim\vimfiles\eclim\plugin\settings_java. vim

### ISSUE THREAD

**Issue by BinFive** [ervandew/eclim#487]
After i installed Eclim_2.6.0 , run :EclimValidate, it shows the following message: "Result: OK, required settings are valid". But when i reopen vim(gvim74), it showed message like this:

Error detected while processing $Vim\vimfiles\eclim\plugin\settings_java.vim:
line  117:
E116: Invalid arguments for function eclim#AddVimSetting

This is really annoying me, anyone knows how to fix this?

**Comment by ervandew** [comment]
How did you install eclim? How did you install the eclim vim files?

**Comment by BinFive** [comment]
I use the windows 10 Build 10586 System, and i followed the official installation steps, using the Graphical Installer to install eclim(the installation was going pretty soomthly). And i let pathogen to manage my plugins, and i didn't really know how the eclim vim files were installed ( i just a beginner with vim).

  I found that there are three eclim.vim files, the first one is in "$Vim\vimfiles\eclim\plugin\" directory, the other is in "$Vim\vimfiles\eclim\autoload\" directory, the last one is in "$Vim\vimfiles\plugin\" directory (the directory is where i use pathogen to download plugins to).

  I had googled this error, someone said may be it because that there are incompatible versions of ecilm's files being loaded. i did try to install eclim before but i failed, and i already deleted the old version...

**Comment by ervandew** [comment]
Try running `:scriptnames` after you start vim to see if you have old eclim vim files installed in some other location.

**Comment by BinFive** [comment]
i already did that, and i only found three eclim.vim files like i said above (i also used the Windows Files Explorer to search, same result.). Any idea what the problem is if it wasn't not some old version causing the trouble?

**Comment by BinFive** [comment]
F-word, i know why! It's the coding problem(it just occur to me),  after i put "set encoding=utf-8" in my _vimrc file, the error disappear! I gotta to admit that i am a newbie. And i am really sorry to bother you, @ervandew. Thanks bro!
