### ISSUE TITLE
Separate eclim vim script plugin from eclim eclipse core integration

### ISSUE THREAD

**Issue by mitermayer** [ervandew/eclim#500]
Would be great if we could separate the vim-script out into its own project and keep this one as the eclipse bindings so that it could be managed by Vundle, plugged, pathogen etc...

**Comment by ervandew** [comment]
There have already been long discussions on why I don't like that idea, sorry.

**Comment by ianks** [comment]
Is there an easy solution for working with vim plugin managers? @ervandew

**Comment by ervandew** [comment]
> Is there an easy solution for working with vim plugin managers?

You can install the eclim vim files to any directory you want, so you could install them in directory compatible with your plugin manager.
