### ISSUE TITLE
Wrong interpretation of tilde (~) by Dvim.files installer argument

### ISSUE THREAD

**Issue by webastien** [ervandew/eclim#505]
When installing eclim with command line, the tilde character given to the argument "Dvim.files" creates a directory called "~" in the current dir, instead of being interpreted as "user home".

Example:
`cd ~/one-directory`
`java -Dvim.files=~/.vim -Declipse.home=/opt/eclipse -jar /tmp/eclim-installer.jar install`

Will create the directory `~/one-directory/~/.vim` (`/home/webastien/one-directory/~/.vim` considering my home dir is `/home/webastien`)

My config:
* Debian 8 "jessie" (vboxed in Mac 10.12.3 / Virtualbox 5.0.32 r112930)
* Installer used: https://github.com/ervandew/eclim/releases/download/2.6.0/eclim_2.6.0.jar
* Eclipse used: http://mirrors.nic.cz/eclipse/technology/epp/downloads/release/neon/1a/eclipse-java-neon-1a-linux-gtk-x86_64.tar.gz

**Comment by ervandew** [comment]
I just released a new installer that should solve this issue. I'm going to close this, but feel free to re-open if the problem persists with the new command line installer.
