### ISSUE TITLE
how to create a python project 

### ISSUE THREAD

**Issue by skadilover** [ervandew/eclim#510]
java.lang.IllegalArgumentException: Unable to find nature for alias 'python'.  Supported aliases include: java=org.eclipse.jdt.core.javanature, javascript=org.eclipse.wst.jsdt.core.
jsNature

when I try create a python project, I got this error. It`s maybe elipse dot not support python, 
are there any guys provider a method to install python support for eclipse on Linux server .
I cannot use elipse GUI on a linux server.

**Comment by ervandew** [comment]
See the note about installing eclipse plugins here:
http://eclim.org/install.html#install-headless

You're going to need to install the pydev plugin using: -installIU org.python.pydev.feature
After you've installed that, you'll need to re-install eclim so that the python support is included.
