### ISSUE TITLE
install eclim with errors on macOS Sierra

### ISSUE THREAD

**Issue by YubaiTao** [ervandew/eclim#516]
The eclipse is the one that extracted from *.tar.gz
Eclipse version: 4.6.3 (neon)
JDK version: 1.8
And the directory I assigned at GUI installer is: "/Applications/Eclipse.app/Contents/Eclipse"
After installation, run `./eclimd` and get:

> ./eclimd
/Library/Java/Home/bin/java -version
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468-11M4833)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)
/Library/Java/Home/bin/java -d64 -Xmx256m -XstartOnFirstThread -jar /Applications/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.equinox.launcher_1.3.201.v20161025-1711.jar --launcher.suppressErrors -debug -clean -refresh -application org.eclim.application
Install location:
    file:/Applications/Eclipse.app/Contents/Eclipse/
Configuration file:
    file:/Applications/Eclipse.app/Contents/Eclipse/configuration/config.ini loaded
Configuration location:
    file:/Applications/Eclipse.app/Contents/Eclipse/configuration/
Framework located:
    file:/Applications/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.osgi_3.11.3.v20170209-1843.jar
Loading extension: reference:file:org.eclipse.osgi.compatibility.state_1.0.200.v20160504-1419.jar
	eclipse.properties not found
Framework classpath:
    file:/Applications/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.osgi_3.11.3.v20170209-1843.jar
    file:/Applications/Eclipse.app/Contents/Eclipse/plugins/  file:/Applications/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.osgi.compatibility.state_1.0.200.v20160504-1419.jar
Debug options:
    file:/Applications/Eclipse.app/Contents/Eclipse/.options not found
Time to load bundles: 75
An error has occurred. See the log file
/Applications/Eclipse.app/Contents/Eclipse/configuration/1495303137440.log.

I also tried install by command line(error shows after build), install by the compiled version of eclim, using Eclipse4.5(Mars)+eclim_2.5.0, none of these works, I'm wondering if it's OS's problem or my setting for eclipse is not correct at somewhere. If anyone SUCCEED on install eclim with macOS sierra, please enlighten me... 

The log file content(part of it):

> !ENTRY org.eclipse.jdt.apt.core 2 0 2017-05-21 01:59:00.308
!MESSAGE Could not resolve module: org.eclipse.jdt.apt.core [203]
  Unresolved requirement: Require-Bundle: org.eclipse.core.runtime; bundle-version="[3.5.100,4.0.0)"
    -> Bundle-SymbolicName: org.eclipse.core.runtime; bundle-version="3.12.0.v20160606-1342"; singleton:="true"
       org.eclipse.core.runtime [87]
         Unresolved requirement: Require-Bundle: org.eclipse.equinox.common; bundle-version="[3.8.0,4.0.0)"; visibility:="reexport"
           -> Bundle-SymbolicName: org.eclipse.equinox.common; bundle-version="3.8.0.v20160509-1230"; singleton:="true"
              org.eclipse.equinox.common [144]
                Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.7))"
  Unresolved requirement: Require-Bundle: org.eclipse.jdt.core; bundle-version="[3.6.0,4.0.0)"
    -> Bundle-SymbolicName: org.eclipse.jdt.core; bundle-version="3.12.3.v20170228-1205"; singleton:="true"
       org.eclipse.jdt.core [208]
         Unresolved requirement: Require-Bundle: org.eclipse.core.resources; bundle-version="[3.3.0,4.0.0)"
           -> Bundle-SymbolicName: org.eclipse.core.resources; bundle-version="3.11.1.v20161107-2032"; singleton:="true"
              org.eclipse.core.resources [86]
                Unresolved requirement: Require-Bundle: org.eclipse.core.expressions; bundle-version="[3.2.0,4.0.0)"
                  -> Bundle-SymbolicName: org.eclipse.core.expressions; bundle-version="3.5.100.v20160418-1621"; singleton:="true"
                     org.eclipse.core.expressions [79]
                       Unresolved requirement: Require-Bundle: org.eclipse.core.runtime; bundle-version="[3.3.0,4.0.0)"
                         -> Bundle-SymbolicName: org.eclipse.core.runtime; bundle-version="3.12.0.v20160606-1342"; singleton:="true"
                Unresolved requirement: Require-Bundle: org.eclipse.core.runtime; bundle-version="[3.12.0,4.0.0)"
                  -> Bundle-SymbolicName: org.eclipse.core.runtime; bundle-version="3.12.0.v20160606-1342"; singleton:="true"
                Unresolved requirement: Require-Bundle: org.eclipse.ant.core; bundle-version="[3.1.0,4.0.0)"; resolution:="optional"
                  -> Bundle-SymbolicName: org.eclipse.ant.core; bundle-version="3.4.100.v20160505-0642"; singleton:="true"
                     org.eclipse.ant.core [64]
                       Unresolved requirement: Require-Bundle: org.eclipse.core.runtime; bundle-version="[3.2.0,4.0.0)"
                         -> Bundle-SymbolicName: org.eclipse.core.runtime; bundle-version="3.12.0.v20160606-1342"; singleton:="true"
                       Unresolved requirement: Require-Bundle: org.eclipse.core.variables; bundle-version="[3.1.0,4.0.0)"
                         -> Bundle-SymbolicName: org.eclipse.core.variables; bundle-version="3.3.0.v20160419-1720"; singleton:="true"
                            org.eclipse.core.variables [88]
                              Unresolved requirement: Require-Bundle: org.eclipse.core.runtime; bundle-version="[3.3.0,4.0.0)"
                                -> Bundle-SymbolicName: org.eclipse.core.runtime; bundle-version="3.12.0.v20160606-1342"; singleton:="true"
                Unresolved requirement: Require-Bundle: org.eclipse.core.filesystem; bundle-version="[1.3.0,2.0.0)"
                  -> Bundle-SymbolicName: org.eclipse.core.filesystem; bundle-version="1.6.1.v20161113-2349"; singleton:="true"
                     org.eclipse.core.filesystem [82]
                       Unresolved requirement: Require-Bundle: org.eclipse.equinox.common; bundle-version="[3.2.0,4.0.0)"
                         -> Bundle-SymbolicName: org.eclipse.equinox.common; bundle-version="3.8.0.v20160509-1230"; singleton:="true"
!ENTRY org.eclipse.ui.externaltools 2 0 2017-05-21 01:59:00.308
!MESSAGE Could not resolve module: org.eclipse.ui.externaltools [403]
  Unresolved requirement: Require-Bundle: org.eclipse.core.resources; bundle-version="[3.2.0,4.0.0)"
    -> Bundle-SymbolicName: org.eclipse.core.resources; bundle-version="3.11.1.v20161107-2032"; singleton:="true"
       org.eclipse.core.resources [86]
         Unresolved requirement: Require-Bundle: org.eclipse.core.expressions; bundle-version="[3.2.0,4.0.0)"
           -> Bundle-SymbolicName: org.eclipse.core.expressions; bundle-version="3.5.100.v20160418-1621"; singleton:="true"
              org.eclipse.core.expressions [79]
                Unresolved requirement: Require-Bundle: org.eclipse.core.runtime; bundle-version="[3.3.0,4.0.0)"
                  -> Bundle-SymbolicName: org.eclipse.core.runtime; bundle-version="3.12.0.v20160606-1342"; singleton:="true"
                     org.eclipse.core.runtime [87]
                       Unresolved requirement: Require-Bundle: org.eclipse.equinox.common; bundle-version="[3.8.0,4.0.0)"; visibility:="reexport"
                         -> Bundle-SymbolicName: org.eclipse.equinox.common; bundle-version="3.8.0.v20160509-1230"; singleton:="true"
                            org.eclipse.equinox.common [144]
                              Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.7))"
         Unresolved requirement: Require-Bundle: org.eclipse.core.runtime; bundle-version="[3.12.0,4.0.0)"
           -> Bundle-SymbolicName: org.eclipse.core.runtime; bundle-version="3.12.0.v20160606-1342"; singleton:="true"
         Unresolved requirement: Require-Bundle: org.eclipse.ant.core; bundle-version="[3.1.0,4.0.0)"; resolution:="optional"
           -> Bundle-SymbolicName: org.eclipse.ant.core; bundle-version="3.4.100.v20160505-0642"; singleton:="true"
              org.eclipse.ant.core [64]
                Unresolved requirement: Require-Bundle: org.eclipse.core.runtime; bundle-version="[3.2.0,4.0.0)"
                  -> Bundle-SymbolicName: org.eclipse.core.runtime; bundle-version="3.12.0.v20160606-1342"; singleton:="true"
                Unresolved requirement: Require-Bundle: org.eclipse.core.variables; bundle-version="[3.1.0,4.0.0)"
                  -> Bundle-SymbolicName: org.eclipse.core.variables; bundle-version="3.3.0.v20160419-1720"; singleton:="true"
                     org.eclipse.core.variables [88]
                       Unresolved requirement: Require-Bundle: org.eclipse.core.runtime; bundle-version="[3.3.0,4.0.0)"
                         -> Bundle-SymbolicName: org.eclipse.core.runtime; bundle-version="3.12.0.v20160606-1342"; singleton:="true"
         Unresolved requirement: Require-Bundle: org.eclipse.core.filesystem; bundle-version="[1.3.0,2.0.0)"
           -> Bundle-SymbolicName: org.eclipse.core.filesystem; bundle-version="1.6.1.v20161113-2349"; singleton:="true"
              org.eclipse.core.filesystem [82]
                Unresolved requirement: Require-Bundle: org.eclipse.equinox.common; bundle-version="[3.2.0,4.0.0)"
                  -> Bundle-SymbolicName: org.eclipse.equinox.common; bundle-version="3.8.0.v20160509-1230"; singleton:="true"
  Unresolved requirement: Require-Bundle: org.eclipse.ui.ide; bundle-version="[3.2.0,4.0.0)"; resolution:="optional"
    -> Bundle-SymbolicName: org.eclipse.ui.ide; bundle-version="3.12.3.v20170119-0935"; singleton:="true"
       org.eclipse.ui.ide [405]
         Unresolved requirement: Require-Bundle: org.eclipse.core.runtime; bundle-version="[3.2.0,4.0.0)"
           -> Bundle-SymbolicName: org.eclipse.core.runtime; bundle-version="3.12.0.v20160606-1342"; singleton:="true"
         Unresolved requirement: Require-Bundle: org.eclipse.core.resources; bundle-version="[3.7.0,4.0.0)"; resolution:="optional"
           -> Bundle-SymbolicName: org.eclipse.core.resources; bundle-version="3.11.1.v20161107-2032"; singleton:="true"
!ENTRY org.eclipse.ui.intro 2 0 2017-05-21 01:59:00.308
!MESSAGE Could not resolve module: org.eclipse.ui.intro [407]
  Unresolved requirement: Import-Package: org.eclipse.e4.core.di.annotations
    -> Export-Package: org.eclipse.e4.core.di.annotations; bundle-version="1.5.0.v20151127-1241"; bundle-symbolic-name="org.eclipse.e4.core.di.annotations"; version="0.0.0"
       org.eclipse.e4.core.di.annotations [95]
         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.8))"
!ENTRY org.eclipse.core.commands 2 0 2017-05-21 01:59:00.308
!MESSAGE Could not resolve module: org.eclipse.core.commands [73]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.7))"
  Unresolved requirement: Require-Bundle: org.eclipse.equinox.common; bundle-version="[3.2.0,4.0.0)"
    -> Bundle-SymbolicName: org.eclipse.equinox.common; bundle-version="3.8.0.v20160509-1230"; singleton:="true"
       org.eclipse.equinox.common [144]
         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.7))"
!ENTRY javax.servlet 2 0 2017-05-21 01:59:00.308
!MESSAGE Could not resolve module: javax.servlet [20]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.7))"
!ENTRY org.eclipse.debug.ui 2 0 2017-05-21 01:59:00.309
!MESSAGE Could not resolve module: org.eclipse.debug.ui [90]
  Unresolved requirement: Require-Bundle: org.eclipse.core.expressions; bundle-version="[3.4.0,4.0.0)"
    -> Bundle-SymbolicName: org.eclipse.core.expressions; bundle-version="3.5.100.v20160418-1621"; singleton:="true"
       org.eclipse.core.expressions [79]
         Unresolved requirement: Require-Bundle: org.eclipse.core.runtime; bundle-version="[3.3.0,4.0.0)"
           -> Bundle-SymbolicName: org.eclipse.core.runtime; bundle-version="3.12.0.v20160606-1342"; singleton:="true"
              org.eclipse.core.runtime [87]
                Unresolved requirement: Require-Bundle: org.eclipse.equinox.common; bundle-version="[3.8.0,4.0.0)"; visibility:="reexport"
                  -> Bundle-SymbolicName: org.eclipse.equinox.common; bundle-version="3.8.0.v20160509-1230"; singleton:="true"
                     org.eclipse.equinox.common [144]
                       Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.7))"
  Unresolved requirement: Import-Package: org.eclipse.ui.forms.widgets
    -> Export-Package: org.eclipse.ui.forms.widgets; bundle-version="3.7.1.v20161220-1635"; bundle-symbolic-name="org.eclipse.ui.forms"; version="0.0.0"
       org.eclipse.ui.forms [404]
         Unresolved requirement: Require-Bundle: org.eclipse.core.runtime; bundle-version="[3.6.0,4.0.0)"
           -> Bundle-SymbolicName: org.eclipse.core.runtime; bundle-version="3.12.0.v20160606-1342"; singleton:="true"
!ENTRY org.eclipse.osgi 4 0 2017-05-21 01:59:00.309
!MESSAGE Application error
!STACK 1
java.lang.IllegalStateException: Unable to acquire application service. Ensure that the org.eclipse.core.runtime bundle is resolved and started (see config.ini).
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:78)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1492)

**Comment by ervandew** [comment]
I'm closing this out since I just released a new installer for eclim that should solve all the issues related to attempting to use the old gui eclim installer against eclipse installed via their gui installer.

The osx support should also be much better.
