### ISSUE TITLE
Eclipse 4.7 Oxygen Support

### ISSUE THREAD

**Issue by kevintownsend** [ervandew/eclim#518]
Is there a plan for supporting Eclipse 4.7? Has anyone looked at what would be involved?

**Comment by ervandew** [comment]
Eclipse 4.7 hasn't been released yet, so there will be no eclim release until that happens. But I do have a branch that works with eclipse 4.7 rc1:

https://github.com/ervandew/eclim/tree/oxygen

**Comment by andreasferber** [comment]
Since Eclipse 4.7 has been released a week ago, is there an ETA when the Eclim update will be officially available?

**Comment by andreasferber** [comment]
I have seen that there's a release available now :-) Thank's for the nice work you are doing :-)
