### ISSUE TITLE
[Not a bug] Is it me or no more annoying cmd prompt popup windows on Windows 10 Creators?

### ISSUE THREAD

**Issue by dimxdim** [ervandew/eclim#527]
Just a sanity check. Is it me or on Windows 10 there are no more cmd prompt popups that normally occur on every completion?
I discovered it by chance setting up eclim+gvim on my Win10 machine and just wanted to ask whether this is normal. I know microsoft changed cmd.exe with Creators update, so maybe that's why...

I havent tested on any previous versions of Windows 10 (Anniversary etc), so I have no base line for comparison.

`:echo system('dir')` still results in a popup though. Eclim uses different mechanism for its communication I suppose?

My setup specs:
gVim 8.0.711 x64 github-win32 build (also no popups on tux / kaoriya builds)
Windows 10 x64 1703 (Creators update)
Eclipse Neon 3 x64
Eclim 2.6.0
oracle java se 1.8.0.131

I have disabled all plugins just to be on the safe side, :`PingEclim` no longer produces the popup cmd window. The output is correct, the completion are correct on a quick helloWorld project.
Eclim daemon is running from Eclipse GUI (show view -> other -> eclimd).

Can anyone reproduce? If so, good news everyone!!! Might as well mention it in the docs/website/etc.
@ervandew thank you for this awesome software!

**Comment by ervandew** [comment]
I'm closing this out since going forward eclim isn't going to support Windows anymore.
