### ISSUE TITLE
ECLIMD $JAVA_VERSION ERROR: JDK 9 + eclipse.buildId=4.7.2.M20171130-0510 

### ISSUE THREAD

**Issue by indran76** [ervandew/eclim#553]
Problem: The below code will return 0 as java version  for JDK 9.0.x which will cause start up problems because it will remove --add-modules arguments when running with JDK 9.0.1 and Latest Eclipse Oxygen

  JAVA_VERSION=$(
    $JAVA -version 2>&1 |
      grep version |
      perl -pe 's|.*"[0-9]\.(.*)\..*".*|\1|'
  )

$ java -version
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)

$ java -version 2>&1 | grep version | perl -pe 's|.*"[0-9]\.(.*)\..*".*|\1|'^C
0

$ /usr/local/java/jdk1.8.0_92/bin/java -version 2>&1 | grep version | perl -pe 's|.*"[0-9]\.(.*)\..*".*|\1|'^C
8

!ENTRY org.eclipse.e4.ui.workbench 4 0 2018-01-18 12:43:12.190
!MESSAGE FrameworkEvent ERROR
!STACK 0
java.lang.NoClassDefFoundError: javax/annotation/PreDestroy
>-------at org.eclipse.e4.core.internal.di.InjectorImpl.disposed(InjectorImpl.java:450)
>-------at org.eclipse.e4.core.internal.di.Requestor.disposed(Requestor.java:156)
>-------at org.eclipse.e4.core.internal.contexts.ContextObjectSupplier$ContextInjectionListener.update(ContextObjectSupplier.java:78)
>-------at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.update(TrackableComputationExt.java:111)
>-------at org.eclipse.e4.core.internal.contexts.TrackableComputationExt.handleInvalid(TrackableComputationExt.java:74)
>-------at org.eclipse.e4.core.internal.contexts.EclipseContext.dispose(EclipseContext.java:178)
>-------at org.eclipse.e4.core.internal.contexts.osgi.EclipseContextOSGi.dispose(EclipseContextOSGi.java:99)
>-------at org.eclipse.e4.core.internal.contexts.osgi.EclipseContextOSGi.bundleChanged(EclipseContextOSGi.java:141)
>-------at org.eclipse.osgi.internal.framework.BundleContextImpl.dispatchEvent(BundleContextImpl.java:908)
>-------at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
>-------at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
>-------at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEventPrivileged(EquinoxEventPublisher.java:213)
>-------at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:120)
>-------at org.eclipse.osgi.internal.framework.EquinoxEventPublisher.publishBundleEvent(EquinoxEventPublisher.java:112)
>-------at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor.publishModuleEvent(EquinoxContainerAdaptor.java:168)
>-------at org.eclipse.osgi.container.Module.publishEvent(Module.java:476)
>-------at org.eclipse.osgi.container.Module.doStop(Module.java:634)
>-------at org.eclipse.osgi.container.Module.stop(Module.java:498)
>-------at org.eclipse.osgi.container.SystemModule.stop(SystemModule.java:202)
>-------at org.eclipse.osgi.internal.framework.EquinoxBundle$SystemBundle$EquinoxSystemModule$1.run(EquinoxBundle.java:165)
>-------at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.ClassNotFoundException: javax.annotation.PreDestroy cannot be found by org.eclipse.e4.core.di_1.6.100.v20170421-1418
>-------at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:433)
>-------at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:395)
>-------at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:387)
>-------at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:150)
>-------at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
>-------... 21 more
!SESSION 2018-01-18 12:47:22.299 -----------------------------------------------
eclipse.buildId=4.7.2.M20171130-0510
java.version=9.0.1
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  --launcher.suppressErrors -refresh -application org.eclim.application
Command-line arguments:  --launcher.suppressErrors -debug -clean -refresh -application org.eclim.application

**Comment by ervandew** [comment]
This has been fixed on the master branch: d4670ec3f0a6f0cddb3cfe2dd69b769b0deab14c
