### ISSUE TITLE
Is that means I can not use eclim on windows10 ?

### ISSUE THREAD

**Issue by MyGitTools** [ervandew/eclim#563]
![eclim](https://user-images.githubusercontent.com/24812722/36071496-127aac24-0f4a-11e8-9258-8295a67bf204.png)
if it works for me, can you help me to build the eclim jar file, my eclipse Version: Oxygen.2 Release (4.7.2)
my gmail:  jerryisruochi@gmail.com

**Comment by ervandew** [comment]
Eclim will no longer work on Windows systems.
