### ISSUE TITLE
running debugger with vim from cli

### ISSUE THREAD

**Issue by shn0by** [ervandew/eclim#566]
not sure if i can post it here, 

i understand you have more important tasks in development of library, was trying to contact you over freenode.net but no luck. 

my main problem is not being able to follow your clear instruction of 
`vim --servername debug`

![vim debug failed](https://user-images.githubusercontent.com/29067013/36931001-93235ca0-1ec6-11e8-9ede-7ca4df46f96c.png)

it s being main setback making me unable to debug my java code. could you please help, was this meant to work from CLI, some threads mentioned that such features are only for gvim.

**Comment by ervandew** [comment]
> Unknown option argument "--servername"

That indicates that your version of vim was not compiled with the `clientserver` option.
