### ISSUE TITLE
OSX - eclim_2.7.2.bin do NOT create symlink "eclim"

### ISSUE THREAD

**Issue by OSTnm** [ervandew/eclim#568]
After installation completed, i only found symlink "eclimd" but no "eclim", not sure if this is an issue.

**Dir:**
/Applications/Eclipse.app/Contents/Eclipse

total 16
drwxr-xr-x  13 xuali2  admin   442 Mar  8 11:35 configuration
drwxr-xr-x   2 xuali2  admin    68 Mar  7 20:59 dropins
lrwxr-xr-x   1 xuali2  admin    55 Mar  7 21:04 eclimd -> /Users/xuan/.p2/pool/plugins/org.eclim_2.7.2/bin/eclimd
-rw-r--r--   1 xuali2  admin  1165 Mar  7 21:04 eclipse.ini
drwxr-xr-x   3 xuali2  admin   102 Mar  7 20:59 plugins
drwxr-xr-x   3 xuali2  admin   102 Mar  7 20:59 readme

that is not very convenient since i must specify "eclim-execuable" && "eclimd-execuable" in emacs at the same time.

- OSX EI Capitan 10.11.6
- Java 1.8
- Eclipse 4.7.2 (Oxygen)

**Comment by ervandew** [comment]
Omitting that symlink was intentional. The vim plugins don't rely on that symlink and I don't think emacs-eclim should be relying on it either. The `~/.eclim/.eclimd_instances` file should be used to determine the `eclim` path to use.
