### ISSUE TITLE
PyDev | Python commands aren't working (RuntimeException)

### ISSUE THREAD

**Issue by smerkousdavid** [ervandew/eclim#569]
It seems to me that the new version of eclim 2.7.2 breaks all PyDev functionality - mind you, this could be a me problem. I've tried rebuilding it twice on two different machines running (Ubuntu 16.04 and Ubuntu 18.04), and it seems to me that the error is not my system, rather the PyDev plugin. The commands for the plugin can be found here: https://github.com/ervandew/eclim/tree/master/org.eclim.pydev/java/org/eclim/plugin/pydev/command/launching. More specifically the add command: https://github.com/ervandew/eclim/blob/master/org.eclim.pydev/java/org/eclim/plugin/pydev/command/launching/AddInterpreterCommand.java. 

Attempting to create the project (which attempts to get all python interpreters)
`:ProjectCreate test -n python`
Or trying to list/add them manually 
`:PythonInterpreterAdd -n python /usr/bin/python`
will result into the following error
```
java.lang.RuntimeException: No command 'python_add_interpreter' found.
while executing command (port: 9091): -editor vim -command python_add_interpreter -p "/usr/bin/python" -n "python"
Press ENTER or type command to continue (Default continue)
```

P.s there was no output from eclimd that could even remotely add to this issue and the error is the same across both machines (fresh install on one)
Any help would be appreciated

Cheers,
David Smerkous

**Comment by ervandew** [comment]
Can you post the eclimd output at startup?
Can you supply what version of pydev you have installed?

**Comment by duseok** [comment]
I have the same problem.
Eclimd output shows that 'Failed to load org.eclim.pydev'
My eclim version is 2.7.2 and pydev version is 6.4.1.201806231219.

**Comment by ervandew** [comment]
This has been fixed on master for a few weeks now, but I've been unable to cut a release since the introduction of java modules as wreaked havoc on all the java commands. If you can build eclim from source then you can get the updates that way.
