### ISSUE TITLE
openjdk compile error

### ISSUE THREAD

**Issue by shenfengok** [ervandew/eclim#574]
ant clean deploy -Declipse.home=/opt/eclipse -Dfile.encoding=UTF-8
Buildfile: /home/shenfeng/download/eclim/build.xml

clean:
   [delete] Deleting directory /home/shenfeng/download/eclim/build
   [delete] Deleting: /home/shenfeng/download/eclim/org.eclim/nailgun/ng

deploy:

gant:
     [echo] ${eclipse}: /opt/eclipse
     [echo] # Skipping org.eclim.adt, missing com.android.ide.eclipse.adt.feature
     [echo] # Skipping org.eclim.cdt, missing org.eclipse.cdt
     [echo] # Skipping org.eclim.dltk, missing org.eclipse.dltk.core
     [echo] # Skipping org.eclim.dltkruby, missing org.eclipse.dltk.ruby
     [echo] # Skipping org.eclim.groovy, missing org.codehaus.groovy.jdt.patch
     [echo] # Skipping org.eclim.pdt, missing org.eclipse.php
     [echo] # Skipping org.eclim.pydev, missing org.python.pydev.feature
     [echo] # Skipping org.eclim.sdt, missing org.scala-ide.sdt.feature
     [echo] # Skipping org.eclim.wst, missing org.eclipse.wst.web_ui.feature
     [echo] Plugins:
     [echo]   org.eclim.jdt
deploy:
deploy.eclipse:
build:
build.eclipse:
init:
     [echo] eclim.version: 2.7.2.2-g09f481a60
     [echo] eclim.release: 2.7.2
org.eclim.jdt.classpath:
------ org.eclim.jdt.classpath
------ init
     [echo]
     [echo] building plugin: org.eclim
    [mkdir] Created dir: /home/shenfeng/download/eclim/build/temp/eclipse/plugins/org.eclim_2.7.2.2-g09f481a60
    [mkdir] Created dir: /home/shenfeng/download/eclim/build/temp/classes/org.eclim
    [javac] Compiling 39 source files to /home/shenfeng/download/eclim/build/temp/classes/org.eclim
      [jar] Building jar: /home/shenfeng/download/eclim/build/temp/eclipse/plugins/org.eclim_2.7.2.2-g09f481a60/eclim.jar
     [copy] Copying 39 files to /home/shenfeng/download/eclim/build/temp/eclipse/plugins/org.eclim_2.7.2.2-g09f481a60
org.eclim.build.eclipse:
     [exec] checking for gcc... gcc
     [exec] checking for C compiler default output file name... a.out
     [exec] checking whether the C compiler works... yes
     [exec] checking whether we are cross compiling... no
     [exec] checking for suffix of executables...
     [exec] checking for suffix of object files... o
     [exec] checking whether we are using the GNU C compiler... yes
     [exec] checking whether gcc accepts -g... yes
     [exec] checking for gcc option to accept ISO C89... none needed
     [exec] checking for gcc option to accept ISO C99... -std=gnu99
     [exec] checking for gethostbyname in -lnsl... yes
     [exec] checking for send in -lsocket... no
     [exec] checking for WriteFile in -lwsock32... no
     [exec] checking how to run the C preprocessor... gcc -std=gnu99 -E
     [exec] checking for grep that handles long lines and -e... /usr/bin/grep
     [exec] checking for egrep... /usr/bin/grep -E
     [exec] checking for ANSI C header files... yes
     [exec] checking for sys/types.h... yes
     [exec] checking for sys/stat.h... yes
     [exec] checking for stdlib.h... yes
     [exec] checking for string.h... yes
     [exec] checking for memory.h... yes
     [exec] checking for strings.h... yes
     [exec] checking for inttypes.h... yes
     [exec] checking for stdint.h... yes
     [exec] checking for unistd.h... yes
     [exec] checking arpa/inet.h usability... yes
     [exec] checking arpa/inet.h presence... yes
     [exec] checking for arpa/inet.h... yes
     [exec] checking netdb.h usability... yes
     [exec] checking netdb.h presence... yes
     [exec] checking for netdb.h... yes
     [exec] checking netinet/in.h usability... yes
     [exec] checking netinet/in.h presence... yes
     [exec] checking for netinet/in.h... yes
     [exec] checking for stdlib.h... (cached) yes
     [exec] checking for string.h... (cached) yes
     [exec] checking sys/socket.h usability... yes
     [exec] checking sys/socket.h presence... yes
     [exec] checking for sys/socket.h... yes
     [exec] checking for unistd.h... (cached) yes
     [exec] checking sys/select.h usability... yes
     [exec] checking sys/select.h presence... yes
     [exec] checking for sys/select.h... yes
     [exec] checking for sys/socket.h... (cached) yes
     [exec] checking types of arguments for select... int,fd_set *,struct timeval *
     [exec] checking for getcwd... yes
     [exec] checking for gethostbyname... yes
     [exec] checking for memset... yes
     [exec] checking for select... yes
     [exec] checking for socket... yes
     [exec] checking for strcasecmp... yes
     [exec] checking for strrchr... yes
     [exec] configure: creating ./config.status
     [exec] config.status: creating Makefile
     [exec] Building ng client.  To build a Windows binary, type 'make ng.exe'
     [exec] gcc -std=gnu99 -g -O2 -lnsl  -s -O3 -o ng src/c/ng.c
     [copy] Copying 1 file to /home/shenfeng/download/eclim/build/temp/eclipse/plugins/org.eclim_2.7.2.2-g09f481a60/bin
      [jar] Updating jar: /home/shenfeng/download/eclim/build/temp/eclipse/plugins/org.eclim_2.7.2.2-g09f481a60/lib/nailgun-0.7.1.jar
------ org.eclim.build.eclipse
     [echo]
     [echo] building plugin: org.eclim.core
    [mkdir] Created dir: /home/shenfeng/download/eclim/build/temp/eclipse/plugins/org.eclim.core_2.7.2.2-g09f481a60
    [mkdir] Created dir: /home/shenfeng/download/eclim/build/temp/classes/org.eclim.core
    [javac] Compiling 70 source files to /home/shenfeng/download/eclim/build/temp/classes/org.eclim.core
      [jar] Building jar: /home/shenfeng/download/eclim/build/temp/eclipse/plugins/org.eclim.core_2.7.2.2-g09f481a60/eclim.core.jar
     [copy] Copying 7 files to /home/shenfeng/download/eclim/build/temp/eclipse/plugins/org.eclim.core_2.7.2.2-g09f481a60
     [echo]
     [echo] building plugin: org.eclim.vimplugin
    [mkdir] Created dir: /home/shenfeng/download/eclim/build/temp/eclipse/plugins/org.eclim.vimplugin_2.7.2.2-g09f481a60
    [mkdir] Created dir: /home/shenfeng/download/eclim/build/temp/classes/org.eclim.vimplugin
    [javac] Compiling 33 source files to /home/shenfeng/download/eclim/build/temp/classes/org.eclim.vimplugin
      [jar] Building MANIFEST-only jar: /home/shenfeng/download/eclim/build/temp/eclipse/plugins/org.eclim.vimplugin_2.7.2.2-g09f481a60/eclim.vimplugin.jar
     [copy] Copying 6 files to /home/shenfeng/download/eclim/build/temp/eclipse/plugins/org.eclim.vimplugin_2.7.2.2-g09f481a60
org.eclim.vimplugin.build.eclipse:
      [jar] Updating jar: /home/shenfeng/download/eclim/build/temp/eclipse/plugins/org.eclim.vimplugin_2.7.2.2-g09f481a60/eclim.vimplugin.jar
------ org.eclim.vimplugin.build.eclipse
     [echo]
     [echo] building plugin: org.eclim.jdt
    [mkdir] Created dir: /home/shenfeng/download/eclim/build/temp/eclipse/plugins/org.eclim.jdt_2.7.2.2-g09f481a60
    [mkdir] Created dir: /home/shenfeng/download/eclim/build/temp/classes/org.eclim.jdt
    [javac] Compiling 101 source files to /home/shenfeng/download/eclim/build/temp/classes/org.eclim.jdt
    [javac] /home/shenfeng/download/eclim/org.eclim.jdt/java/org/eclim/plugin/jdt/command/correct/CodeCorrectCommand.java:398: error: cannot find symbol
    [javac]               JavaElementUtil.applyEdit(src, groupingEdit, true, null);
    [javac]                              ^
    [javac]   symbol:   method applyEdit(ICompilationUnit,TextEdit,boolean,<null>)
    [javac]   location: class JavaElementUtil
    [javac] /home/shenfeng/download/eclim/org.eclim.jdt/java/org/eclim/plugin/jdt/command/include/ImportCommand.java:110: error: cannot find symbol
    [javac]       JavaElementUtil.applyEdit(src, edits, true, null);
    [javac]                      ^
    [javac]   symbol:   method applyEdit(ICompilationUnit,TextEdit,boolean,<null>)
    [javac]   location: class JavaElementUtil
    [javac] /home/shenfeng/download/eclim/org.eclim.jdt/java/org/eclim/plugin/jdt/command/include/ImportCommand.java:130: error: cannot find symbol
    [javac]       JavaElementUtil.applyEdit(src, groupingEdit, true, null);
    [javac]                      ^
    [javac]   symbol:   method applyEdit(ICompilationUnit,TextEdit,boolean,<null>)
    [javac]   location: class JavaElementUtil
    [javac] /home/shenfeng/download/eclim/org.eclim.jdt/java/org/eclim/plugin/jdt/command/include/ImportOrganizeCommand.java:104: error: cannot find symbol
    [javac]       JavaElementUtil.applyEdit(src, edit, true, null);
    [javac]                      ^
    [javac]   symbol:   method applyEdit(ICompilationUnit,TextEdit,boolean,<null>)
    [javac]   location: class JavaElementUtil
    [javac] /home/shenfeng/download/eclim/org.eclim.jdt/java/org/eclim/plugin/jdt/command/include/ImportOrganizeCommand.java:116: error: cannot find symbol
    [javac]       JavaElementUtil.applyEdit(src, groupingEdit, true, null);
    [javac]                      ^
    [javac]   symbol:   method applyEdit(ICompilationUnit,TextEdit,boolean,<null>)
    [javac]   location: class JavaElementUtil
    [javac] /home/shenfeng/download/eclim/org.eclim.jdt/java/org/eclim/plugin/jdt/command/junit/JUnitImplCommand.java:276: error: cannot find symbol
    [javac]         JavaElementUtil.applyEdit(src, edit, true, null);
    [javac]                        ^
    [javac]   symbol:   method applyEdit(ICompilationUnit,MultiTextEdit,boolean,<null>)
    [javac]   location: class JavaElementUtil
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 6 errors

BUILD FAILED
/home/shenfeng/download/eclim/build.xml:32: The following error occurred while executing this line:
/home/shenfeng/download/eclim/build.xml:163: : Compile failed; see the compiler error output for details.

**Comment by ervandew** [comment]
What version of eclipse are you attempt to compile against?

**Comment by shenfengok** [comment]
@ervandew   http://archive.eclipse.org/technology/epp/downloads/release/juno/SR1/eclipse-java-juno-SR1-linux-gtk-x86_64.tar.gz

**Comment by ervandew** [comment]
I think eclim 2.2.7 is the last version that supported Juno, so if you want to compile eclim against that version of eclipse, you can try the following first:

    $ git checkout 2.2.7

**Comment by shenfengok** [comment]
OK,thank you a lot @ervandew
