### ISSUE TITLE
"-d64" command line argument was removed

### ISSUE THREAD

**Issue by MrQubo** [ervandew/eclim#575]
The "-d64" (and "-d32") command line arguments were removed from JDK 10.
Because of this eclimd cannot be started. It displays error
`Your jvm does not support the architecture required  for the version of eclipse you have installed: -d64`.

**Comment by ervandew** [comment]
fixed on master yesterday: ervandew/eclim@3b04188ef4849006cc0bd66e648efdeb4deb40d7

**Comment by MrQubo** [comment]
Thanks. I'll switch to git version.
