### ISSUE TITLE
Setup vim + eclim + checkstyle

### ISSUE THREAD

**Issue by mightymicha** [ervandew/eclim#581]
Hi, when I try to invoke :Checkstyle inside a Java project, I get the following error message:

> com.puppycrawl.tools.checkstyle.api.CheckstyleException: Property 'fileExtensions' in module Checker does not exist, please check the documentation
while executing command (port: 9091): -editor vim -command java_checkstyle -p "static-metric-solver" -f 

I configured eclim with :WorkSpaceSettings.
The config file which I used was this one:
https://raw.githubusercontent.com/checkstyle/checkstyle/master/src/main/resources/google_checks.xml

**Comment by ervandew** [comment]
eclim is pretty far behind on its checkstyle version. my guess is that's the issue. I'll upgrade it when i get the chance.

**Comment by mightymicha** [comment]
Thanks a lot!
