### ISSUE TITLE
Unable to install eclim : ASCII error

### ISSUE THREAD

**Issue by 0pendev** [ervandew/eclim#587]
While trying to install eclipse I get the following error after selecting 0 for the Java development : 

`running: ['java', '-Djava.net.useSystemProxies=true', '-jar', '/home/opendev/Documents/softwares/eclipse/plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar', '-initialize', '-debug'] ... 
Traceback (most recent call last):
  File "/tmp/eclim-installer.DfIZ/install", line 1205, in <module>
    main()
  File "/tmp/eclim-installer.DfIZ/install", line 96, in main
    install(options, eclim)
  File "/tmp/eclim-installer.DfIZ/install", line 116, in install
    step_dependencies(options, eclipse, plugins)
  File "/tmp/eclim-installer.DfIZ/install", line 361, in step_dependencies
    eclipse.gc()
  File "/tmp/eclim-installer.DfIZ/install", line 921, in gc
    '-application', 'org.eclipse.equinox.p2.garbagecollector.application',
  File "/tmp/eclim-installer.DfIZ/install", line 929, in execute
    self._initialize()
  File "/tmp/eclim-installer.DfIZ/install", line 900, in _initialize
    info = self.execute('-initialize', '-debug')
  File "/tmp/eclim-installer.DfIZ/install", line 936, in execute
    stdout, stderr = execute(cmd)
  File "/tmp/eclim-installer.DfIZ/install", line 624, in execute
    stdout = stdout.decode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 857: ordinal not in range(128)
`

**Comment by ervandew** [comment]
Can you run the following command and post the resulting output?

    $ java \
        -Djava.net.useSystemProxies=true \
        -jar /home/opendev/Documents/softwares/eclipse/plugins/org.eclipse.equinox.launcher_1.4.0.v20161219-1356.jar \
        -initialize \
        -debug

**Comment by 0pendev** [comment]
Here is the output : 

Install location:
    file:/home/opendev/Documents/softwares/eclipse/
Configuration file:
    file:/home/opendev/Documents/softwares/eclipse/configuration/config.ini loaded
Configuration location:
    file:/home/opendev/Documents/softwares/eclipse/configuration/
Framework located:
    file:/home/opendev/Documents/softwares/eclipse/plugins/org.eclipse.osgi_3.12.100.v20180210-1608.jar
Loading extension: reference:file:org.eclipse.osgi.compatibility.state_1.1.0.v20170516-1513.jar
	eclipse.properties not found
Framework classpath:
    file:/home/opendev/Documents/softwares/eclipse/plugins/org.eclipse.osgi_3.12.100.v20180210-1608.jar
    file:/home/opendev/Documents/softwares/eclipse/plugins/
    file:/home/opendev/Documents/softwares/eclipse/plugins/org.eclipse.osgi.compatibility.state_1.1.0.v20170516-1513.jar
Debug options:
    file:/home/opendev/Téléchargements/.options not found
Time to load bundles: 6
org.eclipse.m2e.logback.configuration: The org.eclipse.m2e.logback.configuration bundle was activated before the state location was initialized.  Will retry after the state location is initialized.

**Comment by N-injin** [comment]
I have the same problem here.
