### ISSUE TITLE
:JavaRename does not work most of the time, but sometimes it works

### ISSUE THREAD

**Issue by ludwignagelhus** [ervandew/eclim#596]
I enter the command like this
:JavaRename
In the console at the bottom I am asked to type 'e' to confirm my renaming of this class. I type 'e' and press 'enter'. Most of the time nothing happens, without any message explaining that something the renaming cannot be done because of reason x.
Other times it works fine.

Anybody know what might be going on or where I could look to find the problem?

**Comment by dansomething** [comment]
I've noticed this problem seems to occur when there's a compile error. I usually make sure there are no compile issues before I attempt the rename and then its fine.
