### ISSUE TITLE
Region is guarded, cannot modify E463

### ISSUE THREAD

**Issue by void-m4110c** [ervandew/eclim#600]
I use gvim embedded in eclipse. If the Java Code Completer finds an issue (e.g. a missing semi-colon at the end of the line), I can not modify the code in that region anymore. I get the error message: E463: Region is guarded, cannot modify
Here's a screen shot:
![e463](https://user-images.githubusercontent.com/43680093/49175961-0ca3f000-f34a-11e8-8cca-0f89d911b436.png)

_Originally posted by @mickmattes in https://github.com/ervandew/eclim/issues/540#issuecomment-442566698_

**Comment by mickmattes** [comment]
Re-bump!

**Comment by simlei** [comment]
is this perhaps resolved by now? Last I installed eclim, this was driving me nuts. Not only semicolons as above; e.g. editing import statements were guarded for me, too. Anyone else had that issue?
**Let me clarify that I have not tested this for quite a while now**

**Comment by ervandew** [comment]
Unfortunately, due to a lack of time to dedicate to maintenance, I've removed several eclim plugins, and one of them is the vimplugin (embedded vim) support.

**Comment by simlei** [comment]
Could connecting to a running eclim instance (headless or not) via standalone vim still work, or is it also implicated?

**Comment by ervandew** [comment]
I was under the impression that this bug was only related to the embedded gvim, so I presume that using standalone vim doesn't suffer from this issue.
