### ISSUE TITLE
JavaCorrect: ClassCastException in SerialVersionSubProcessor

### ISSUE THREAD

**Issue by lbrayner** [ervandew/eclim#613]
This exception is thrown if you try to run `JavaCorrect` on a class implementing `java.io.Serializable` without a `serialVersionUID`:

~~~
java.lang.ClassCastException: class org.eclim.plugin.jdt.command.correct.ProblemLocation cannot be cast to class org.eclipse.jdt.internal.ui.text.correction.ProblemLocationCore (org.eclim.plugin.jdt.command.correct.ProblemLocation is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @    4ef28a1a; org.eclipse.jdt.internal.ui.text.correction.ProblemLocationCore is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @13cfa1ec)
    at org.eclipse.jdt.internal.corext.fix.PotentialProgrammingProblemsFix.createMissingSerialVersionFixes(PotentialProgrammingProblemsFix.java:53) ~[?:?]
    at org.eclipse.jdt.internal.ui.text.correction.SerialVersionSubProcessor.getSerialVersionProposals(SerialVersionSubProcessor.java:94) ~[?:?]
~~~

This is because `IProblemLocation` is cast to `org.eclipse.jdt.internal.ui.text.correction.ProblemLocationCore by `org.eclipse.jdt.internal.ui.text.correction.SerialVersionSubProcessor`.

I patched this in my fork of eclim: https://github.com/lbrayner/eclim/commit/2287f375c7dfec4fd69e41a2ec65b3e2a3038006.

**Comment by ervandew** [comment]
Thanks! I solved it a wee bit differently with the expectation that some other edge case may pop up in the future.
