### ISSUE TITLE
Java code completion doesn't work

### ISSUE THREAD

**Issue by TV12mac** [ervandew/eclim#614]
I did the basic stuff first validating the settings (it said everything seemed fine)
I also checked that it could see the project
Name:      HelloWorld
Path:     /Desktop/ProgrammingStuff/JavaClassesAndProjects/HelloWorld
Workspace: /Users/(username)/eclipse-workspace
Open:      true
Natures:   java

I was going through the getting started eclim tutorial and then when trying to complete code this occurred

Error detected while processing function eclim#java#complete#CodeComplete[6]..eclim#lang#SilentUpdate[33]..function eclim#java#complete#CodeComplete[6]..eclim#lang#SilentUpdate:
E565: Not allowed to change text or change window:           silent noautocmd update
E171: Missing :endif
Java Model Exception: Java Model Status [Index out of bounds]
while executing command (port: 9091): -editor vim -command java_complete -p "HelloWorld" -f "src/java/org/test/TestMain.java" -o 94 -e utf-8 -l compact

I checked with the troubleshooting FAQ and tmk it didn't contain anything like this.
Im not sure how to handle E565

**Comment by ervandew** [comment]
Looks like this is a new problem introduced by the latest version of vim. I just started getting this error after upgrading (8.2.1989 -> 8.2.2489).

I'll look into this as soon as I get a chance.

**Comment by TV12mac** [comment]
I tried testing it again and the same error occurs except I have vim 8.2.2500 this time

**Comment by TV12mac** [comment]
Yup it works now! Thank you so much 😄
